"""Personal gear data: FPS weapons and armor sets for Star Citizen."""

# FPS WEAPONS - base variants with their skin/color variants grouped
# Structure: base weapon -> list of variants
# Locations: where to buy or find

FPS_WEAPONS = [
    # === PISTOLS ===
    {"id": "arclight-pistol", "name": "Arclight Pistol", "type": "Pistol", "size": 1, "manufacturer": "Klaus & Werner",
     "damage": 18, "ammo": 30, "fire_rate": "Semi/Burst", "effective_range": "50m",
     "description": "Versatile laser pistol. 30-round battery, single/3-round burst. PvP favorite.",
     "price_auec": 4850,
     "locations": ["Live Fire Weapons (most stations)", "Looted from NPCs"],
     "variants": ["Arclight \"Boneyard\" Pistol", "Arclight \"Desert Shadow\" Pistol", "Arclight \"Executive Edition\" Pistol", "Arclight \"Glimmer\" Pistol", "Arclight \"Midnight\" Pistol", "Arclight \"Nightstalker\" Pistol", "Arclight \"Stormfall\" Pistol", "Arclight \"Warhawk\" Pistol"]},

    {"id": "lh86-pistol", "name": "LH86 Pistol", "type": "Pistol", "size": 1, "manufacturer": "Kastak Arms",
     "damage": 20, "ammo": 20, "fire_rate": "Full Auto", "effective_range": "30m",
     "description": "Fully automatic ballistic pistol. High rate of fire, good for close combat.",
     "price_auec": 5200,
     "locations": ["Live Fire Weapons (Lorville)", "Live Fire Weapons (ArcCorp)"],
     "variants": ["LH86 \"Boneyard\" Pistol", "LH86 \"Desert Shadow\" Pistol", "LH86 \"Executive Edition\" Pistol", "LH86 \"Luckbringer\" Pistol", "LH86 \"Nightstalker\" Pistol", "LH86 \"Permafrost\" Pistol", "LH86 \"Scorched\" Pistol", "LH86 \"Stormfall\" Pistol", "LH86 \"Warhawk\" Pistol"]},

    {"id": "yubarev-pistol", "name": "Yubarev Pistol", "type": "Pistol", "size": 1, "manufacturer": "Gemini",
     "damage": 22, "ammo": 12, "fire_rate": "Semi-Auto", "effective_range": "45m",
     "description": "High-damage semi-auto ballistic pistol. Reliable sidearm.",
     "price_auec": 4400,
     "locations": ["Live Fire Weapons (most stations)", "Looted from NPCs"],
     "variants": ["Yubarev \"Deadeye\" Pistol", "Yubarev \"Igniter\" Pistol", "Yubarev \"Mirage\" Pistol", "Yubarev \"Venom\" Pistol"]},

    {"id": "coda-pistol", "name": "Coda Pistol", "type": "Pistol", "size": 1, "manufacturer": "Behring",
     "damage": 30, "ammo": 8, "fire_rate": "Semi-Auto", "effective_range": "55m",
     "description": "Heavy-hitting ballistic pistol. Highest pistol damage per shot.",
     "price_auec": 5800,
     "locations": ["Live Fire Weapons (Port Tressler)", "Live Fire Weapons (Everus Harbor)"],
     "variants": ["Coda \"Ascension\" Pistol", "Coda \"Big Boss\" Pistol", "Coda \"Nighthawk\" Pistol", "Coda \"Ultraviolet\" Pistol"]},

    {"id": "s38-pistol", "name": "S-38 Pistol", "type": "Pistol", "size": 1, "manufacturer": "Behring",
     "damage": 24, "ammo": 15, "fire_rate": "Semi-Auto", "effective_range": "40m",
     "description": "Reliable semi-auto ballistic pistol. Clean design, solid performance.",
     "price_auec": 4200,
     "locations": ["Live Fire Weapons (most stations)"],
     "variants": ["S-38 \"One Empire\" Pistol", "S-38 \"Scorched\" Pistol"]},

    {"id": "pulse-laser-pistol", "name": "Pulse Laser Pistol", "type": "Pistol", "size": 1, "manufacturer": "Lightning Bolt Co.",
     "damage": 14, "ammo": 35, "fire_rate": "Semi-Auto", "effective_range": "35m",
     "description": "Compact energy pistol. Good for sustained engagements.",
     "price_auec": 3800,
     "locations": ["Live Fire Weapons (Area 18)", "Live Fire Weapons (Orison)"],
     "variants": ["Pulse \"ArcCorp\" Pistol", "Pulse \"Crusader\" Pistol", "Pulse \"Greycat\" Pistol", "Pulse \"Hurston\" Pistol", "Pulse \"microTech\" Pistol"]},

    # === SMGs ===
    {"id": "p8-smg", "name": "P8-SC SMG", "type": "SMG", "size": 1, "manufacturer": "Behring",
     "damage": 16, "ammo": 30, "fire_rate": "Full Auto", "effective_range": "40m",
     "description": "High DPS submachine gun. Meta weapon for CQB. Customizable with attachments.",
     "price_auec": 8200,
     "locations": ["Cutter's Rig (Hurston)", "Live Fire Weapons (most stations)", "Looted from security NPCs"],
     "variants": ["P8-SC \"Boneyard\" SMG", "P8-SC \"Desert Shadow\" SMG", "P8-SC \"Epoque\" SMG", "P8-SC \"Executive Edition\" SMG", "P8-SC \"Midnight\" SMG", "P8-SC \"Nightstalker\" SMG", "P8-SC \"Red Alert\" SMG", "P8-SC \"Stormfall\" SMG", "P8-SC \"Warhawk\" SMG"]},

    {"id": "ripper-smg", "name": "Ripper SMG", "type": "SMG", "size": 1, "manufacturer": "Verified Offworld Laser Technologies",
     "damage": 12, "ammo": 45, "fire_rate": "Full Auto", "effective_range": "35m",
     "description": "Rapid-fire laser SMG. Large ammo pool, sustained fire capability.",
     "price_auec": 8900,
     "locations": ["Live Fire Weapons (ARC-L1)", "Live Fire Weapons (CRU-L5)"],
     "variants": ["Ripper \"Sunblock\" SMG"]},

    {"id": "custodian-smg", "name": "Custodian SMG", "type": "SMG", "size": 1, "manufacturer": "Behring",
     "damage": 14, "ammo": 60, "fire_rate": "Full Auto", "effective_range": "45m",
     "description": "Laser SMG with large battery. Good sustained damage output.",
     "price_auec": 7800,
     "locations": ["Live Fire Weapons (Port Olisar)", "Live Fire Weapons (Baijini Point)"],
     "variants": ["Custodian \"Boneyard\" SMG", "Custodian \"Brimstone\" SMG", "Custodian \"Desert Shadow\" SMG", "Custodian \"Executive Edition\" SMG", "Custodian \"Midnight\" SMG", "Custodian \"Nightstalker\" SMG", "Custodian \"Scorched\" SMG", "Custodian \"Warhawk\" SMG"]},

    {"id": "c54-smg", "name": "C54 SMG", "type": "SMG", "size": 2, "manufacturer": "Kastak Arms",
     "damage": 22, "ammo": 30, "fire_rate": "Full Auto/Burst", "effective_range": "55m",
     "description": "Compact ballistic assault weapon. Good balance of damage and handling.",
     "price_auec": 9500,
     "locations": ["Live Fire Weapons (Grim HEX)", "Looted from outlaws"],
     "variants": ["C54 \"Justified\" SMG", "C54 \"Luckbringer\" SMG", "C54 \"Scorched\" SMG", "C54 \"Starchaser\" SMG"]},

    {"id": "lumin-v-smg", "name": "Lumin V SMG", "type": "SMG", "size": 1, "manufacturer": "Lightning Bolt Co.",
     "damage": 13, "ammo": 50, "fire_rate": "Full Auto", "effective_range": "35m",
     "description": "Compact energy SMG. Lightweight with good sustained fire.",
     "price_auec": 6800,
     "locations": ["Live Fire Weapons (most stations)"],
     "variants": ["Lumin V \"Valor\" SMG"]},

    {"id": "quartz-smg", "name": "Quartz Energy SMG", "type": "SMG", "size": 1, "manufacturer": "Lightning Bolt Co.",
     "damage": 11, "ammo": 55, "fire_rate": "Full Auto", "effective_range": "30m",
     "description": "High-capacity energy SMG. Multiple faction-branded variants.",
     "price_auec": 5500,
     "locations": ["Faction-specific shops"],
     "variants": ["Quartz \"ArcCorp\" SMG", "Quartz \"Crusader\" SMG", "Quartz \"Hurston\" SMG", "Quartz \"microTech\" SMG", "Quartz \"Black Op\" SMG", "Quartz \"Deadfall\" SMG", "Quartz \"Lumen\" SMG"]},

    # === ASSAULT RIFLES ===
    {"id": "p4-ar", "name": "P4-AR Rifle", "type": "Assault Rifle", "size": 2, "manufacturer": "Behring",
     "damage": 20, "ammo": 40, "fire_rate": "Full Auto/Semi", "effective_range": "65m",
     "description": "Classic ballistic assault rifle. 40-round mag, highly customizable. Best beginner weapon.",
     "price_auec": 13800,
     "locations": ["Live Fire Weapons (all stations)", "Looted from NPCs"],
     "variants": ["P4-AR \"Boneyard\" Rifle", "P4-AR \"Desert Shadow\" Rifle", "P4-AR \"Nightstalker\" Rifle", "P4-AR \"Warhawk\" Rifle", "P4-AR \"Fortuna\" Rifle"]},

    {"id": "karna-rifle", "name": "Karna Rifle", "type": "Assault Rifle", "size": 2, "manufacturer": "Kastak Arms",
     "damage": 25, "ammo": 60, "fire_rate": "Full Auto", "effective_range": "60m",
     "description": "Powerful laser assault rifle. Strong for PvE and PvP.",
     "price_auec": 17500,
     "locations": ["Live Fire Weapons (Lorville)", "Live Fire Weapons (CRU-L4)"],
     "variants": ["Karna \"Ascension\" Rifle", "Karna \"Brimstone\" Rifle", "Karna \"Fate\" Rifle", "Karna \"Rager\" Rifle", "Karna \"Scorched\" Rifle", "Karna \"Valor\" Rifle"]},

    {"id": "gallant-rifle", "name": "Gallant Rifle", "type": "Assault Rifle", "size": 2, "manufacturer": "Klaus & Werner",
     "damage": 19, "ammo": 50, "fire_rate": "Full Auto", "effective_range": "60m",
     "description": "Energy assault rifle with good accuracy and handling.",
     "price_auec": 15200,
     "locations": ["Live Fire Weapons (most stations)"],
     "variants": ["Gallant \"Boneyard\" Rifle", "Gallant \"Desert Shadow\" Rifle", "Gallant \"Executive Edition\" Rifle", "Gallant \"Midnight\" Rifle", "Gallant \"Nightstalker\" Rifle", "Gallant \"Red Alert\" Rifle", "Gallant \"Stormfall\" Rifle", "Gallant \"Warhawk\" Rifle"]},

    {"id": "s71-rifle", "name": "S71 Rifle", "type": "Assault Rifle", "size": 2, "manufacturer": "Behring",
     "damage": 30, "ammo": 20, "fire_rate": "Semi-Auto", "effective_range": "80m",
     "description": "Semi-auto marksman rifle. High damage per shot, preferred for long range.",
     "price_auec": 15200,
     "locations": ["Cutter's Rig (Hurston)", "Live Fire Weapons (HUR-L1)"],
     "variants": ["S71 \"Ascension\" Rifle", "S71 \"Bullseye\" Rifle", "S71 \"Justified\" Rifle", "S71 \"Scorched\" Rifle"]},

    {"id": "parallax-ar", "name": "Parallax Energy Assault Rifle", "type": "Assault Rifle", "size": 2, "manufacturer": "Lightning Bolt Co.",
     "damage": 18, "ammo": 45, "fire_rate": "Full Auto", "effective_range": "70m",
     "description": "Versatile medium/long range laser assault rifle. Multiple faction variants.",
     "price_auec": 16800,
     "locations": ["Live Fire Weapons (New Babbage)", "Live Fire Weapons (Area 18)"],
     "variants": ["Parallax \"ArcCorp\" Rifle", "Parallax \"Crusader\" Rifle", "Parallax \"Hurston\" Rifle", "Parallax \"microTech\" Rifle", "Parallax \"Sanguine\" Rifle", "Parallax \"Shock Trooper\" Rifle", "Parallax \"Sunstone\" Rifle"]},

    {"id": "killshot-rifle", "name": "Killshot Rifle", "type": "Assault Rifle", "size": 2, "manufacturer": "Kastak Arms",
     "damage": 26, "ammo": 25, "fire_rate": "Full Auto", "effective_range": "55m",
     "description": "Hard-hitting ballistic assault rifle. Favored by combat veterans.",
     "price_auec": 14500,
     "locations": ["Live Fire Weapons (Lorville)", "Grim HEX"],
     "variants": ["Killshot \"Bleach\" Rifle", "Killshot \"Bloody\" Rifle", "Killshot \"Goodnight\" Rifle", "Killshot \"Payback\" Rifle"]},

    # === LMGs ===
    {"id": "f55-lmg", "name": "F55 LMG", "type": "LMG", "size": 3, "manufacturer": "Behring",
     "damage": 20, "ammo": 100, "fire_rate": "Full Auto (Gatling)", "effective_range": "50m",
     "description": "Handheld ballistic gatling gun. Extreme suppression capability.",
     "price_auec": 22400,
     "locations": ["Live Fire Weapons (Lorville)", "Live Fire Weapons (CRU-L4)"],
     "variants": ["F55 \"Deadlock\" LMG", "F55 \"Mark I\" LMG", "F55 \"Scorched\" LMG", "F55 \"Starchaser\" LMG", "F55 \"Valor\" LMG"]},

    {"id": "fs9-lmg", "name": "FS-9 LMG", "type": "LMG", "size": 3, "manufacturer": "Kastak Arms",
     "damage": 22, "ammo": 80, "fire_rate": "Full Auto", "effective_range": "55m",
     "description": "Heavy ballistic LMG. Great for group combat.",
     "price_auec": 20600,
     "locations": ["Cutter's Rig (Hurston)", "Looted from NPCs"],
     "variants": ["FS-9 \"Evergreen\" LMG", "FS-9 \"Stoneface\" LMG", "FS-9 \"Blacklist\" LMG"]},

    {"id": "demeco-lmg", "name": "Demeco LMG", "type": "LMG", "size": 3, "manufacturer": "Verified Offworld Laser Technologies",
     "damage": 16, "ammo": 165, "fire_rate": "Full Auto", "effective_range": "55m",
     "description": "Laser LMG with massive battery. Sustained suppressive fire.",
     "price_auec": 24800,
     "locations": ["Live Fire Weapons (CRU-L5)", "Live Fire Weapons (ARC-L2)"],
     "variants": ["Demeco \"Red Alert\" LMG", "Demeco \"Ultraviolet\" LMG"]},

    {"id": "fresnel-lmg", "name": "Fresnel Energy LMG", "type": "LMG", "size": 3, "manufacturer": "Lightning Bolt Co.",
     "damage": 15, "ammo": 120, "fire_rate": "Full Auto", "effective_range": "50m",
     "description": "Energy LMG with massive battery capacity. Good suppression.",
     "price_auec": 21000,
     "locations": ["Live Fire Weapons (Area 18)", "Live Fire Weapons (New Babbage)"],
     "variants": ["Fresnel \"Deepwater\" LMG", "Fresnel \"Elysium\" LMG", "Fresnel \"Icebox\" LMG", "Fresnel \"Molten\" LMG", "Fresnel \"Shadow Gild\" LMG"]},

    {"id": "pulverizer-lmg", "name": "Pulverizer LMG", "type": "LMG", "size": 3, "manufacturer": "Kastak Arms",
     "damage": 24, "ammo": 75, "fire_rate": "Full Auto", "effective_range": "45m",
     "description": "Heavy ballistic LMG with high damage per round.",
     "price_auec": 23500,
     "locations": ["Live Fire Weapons (Lorville)", "Grim HEX"],
     "variants": ["Pulverizer \"Bleach\" LMG", "Pulverizer \"Bloody\" LMG", "Pulverizer \"Mustard\" LMG", "Pulverizer \"Payback\" LMG"]},

    # === SHOTGUNS ===
    {"id": "ravager-shotgun", "name": "Ravager-212 Twin Shotgun", "type": "Shotgun", "size": 2, "manufacturer": "Apocalypse Arms",
     "damage": 80, "ammo": 8, "fire_rate": "Pump-Action", "effective_range": "15m",
     "description": "Devastating pump-action shotgun. One-shot potential at close range.",
     "price_auec": 13500,
     "locations": ["Live Fire Weapons (Grim HEX)", "Looted from outlaws"],
     "variants": ["Ravager-212 \"Bright Star\" Shotgun", "Ravager-212 \"Outcast\" Shotgun", "Ravager-212 \"Red Alert\" Shotgun", "Ravager-212 \"Scorched\" Shotgun"]},

    {"id": "br2-shotgun", "name": "BR-2 Shotgun", "type": "Shotgun", "size": 2, "manufacturer": "Behring",
     "damage": 60, "ammo": 6, "fire_rate": "Semi-Auto", "effective_range": "20m",
     "description": "Semi-automatic shotgun. Good for rapid follow-up shots.",
     "price_auec": 11200,
     "locations": ["Live Fire Weapons (Lorville)", "Live Fire Weapons (Area 18)"],
     "variants": ["BR-2 \"Permafrost\" Shotgun"]},

    {"id": "devastator-shotgun", "name": "Devastator Shotgun", "type": "Shotgun", "size": 2, "manufacturer": "Apocalypse Arms",
     "damage": 70, "ammo": 10, "fire_rate": "Semi-Auto", "effective_range": "18m",
     "description": "Semi-auto shotgun with large magazine. Relentless close-range firepower.",
     "price_auec": 14200,
     "locations": ["Live Fire Weapons (Grim HEX)", "Live Fire Weapons (Lorville)"],
     "variants": ["Devastator \"Boneyard\" Shotgun", "Devastator \"Brimstone\" Shotgun", "Devastator \"Desert Shadow\" Shotgun", "Devastator \"Executive Edition\" Shotgun", "Devastator \"Midnight\" Shotgun", "Devastator \"Nightstalker\" Shotgun", "Devastator \"Rager\" Shotgun", "Devastator \"Starchaser\" Shotgun", "Devastator \"Warhawk\" Shotgun"]},

    {"id": "r97-shotgun", "name": "R97 Shotgun", "type": "Shotgun", "size": 2, "manufacturer": "Kastak Arms",
     "damage": 65, "ammo": 7, "fire_rate": "Semi-Auto", "effective_range": "15m",
     "description": "Compact ballistic shotgun. Quick handling for tight spaces.",
     "price_auec": 10800,
     "locations": ["Live Fire Weapons (Lorville)", "Grim HEX"],
     "variants": ["R97 \"Kismet\" Shotgun", "R97 \"Righteous\" Shotgun", "R97 \"Scorched\" Shotgun"]},

    {"id": "prism-shotgun", "name": "Prism Laser Shotgun", "type": "Shotgun", "size": 2, "manufacturer": "Lightning Bolt Co.",
     "damage": 45, "ammo": 20, "fire_rate": "Semi-Auto", "effective_range": "25m",
     "description": "Energy shotgun with tight spread. More range than ballistic shotguns.",
     "price_auec": 12400,
     "locations": ["Live Fire Weapons (New Babbage)", "Live Fire Weapons (Port Tressler)"],
     "variants": ["Prism \"ArcCorp\" Shotgun", "Prism \"Crusader\" Shotgun", "Prism \"Deep Sea\" Shotgun", "Prism \"Firesteel\" Shotgun", "Prism \"Hazard\" Shotgun", "Prism \"Hurston\" Shotgun", "Prism \"microTech\" Shotgun"]},

    # === SNIPER RIFLES ===
    {"id": "arrowhead-sniper", "name": "Arrowhead Sniper Rifle", "type": "Sniper Rifle", "size": 3, "manufacturer": "Klaus & Werner",
     "damage": 80, "ammo": 8, "fire_rate": "Bolt-Action", "effective_range": "200m",
     "description": "Long-range sniper rifle. Community favorite for precision engagements.",
     "price_auec": 21200,
     "locations": ["Live Fire Weapons (New Babbage)", "Live Fire Weapons (HUR-L5)"],
     "variants": ["Arrowhead \"Boneyard\" Sniper", "Arrowhead \"Desert Shadow\" Sniper", "Arrowhead \"Executive\" Sniper", "Arrowhead \"Lamplighter\" Sniper", "Arrowhead \"Midnight\" Sniper", "Arrowhead \"Nightstalker\" Sniper", "Arrowhead \"Stormfall\" Sniper", "Arrowhead \"Warhawk\" Sniper"]},

    {"id": "p6-lr-sniper", "name": "P6-LR Sniper Rifle", "type": "Sniper Rifle", "size": 3, "manufacturer": "Behring",
     "damage": 100, "ammo": 5, "fire_rate": "Bolt-Action", "effective_range": "250m",
     "description": "50-cal ballistic sniper. 8x scope + rangefinder. Highest FPS damage.",
     "price_auec": 19400,
     "locations": ["Live Fire Weapons (Port Tressler)", "Live Fire Weapons (CRU-L1)"],
     "variants": ["P6-LR \"Archangel\" Sniper", "P6-LR \"Rime\" Sniper", "P6-LR \"Blacklist\" Sniper", "P6-LR \"Gideon\" Sniper"]},

    {"id": "a03-sniper", "name": "A03 Sniper Rifle", "type": "Sniper Rifle", "size": 3, "manufacturer": "Gemini",
     "damage": 42, "ammo": 15, "fire_rate": "Semi-Auto", "effective_range": "150m",
     "description": "Semi-auto sniper with larger magazine. Good for follow-up shots.",
     "price_auec": 18600,
     "locations": ["Live Fire Weapons (Baijini Point)", "Live Fire Weapons (ARC-L1)"],
     "variants": ["A03 \"Canuto\" Sniper", "A03 \"Lodestone\" Sniper", "A03 \"Luckbringer\" Sniper", "A03 \"Red Alert\" Sniper", "A03 \"Scorched\" Sniper", "A03 \"Wildwood\" Sniper"]},

    {"id": "atzkav-sniper", "name": "Atzkav Sniper Rifle", "type": "Sniper Rifle", "size": 3, "manufacturer": "Lightning Bolt Co.",
     "damage": 55, "ammo": 10, "fire_rate": "Semi-Auto", "effective_range": "180m",
     "description": "Energy sniper with EMP effect. Disrupts electronics on hit.",
     "price_auec": 23500,
     "locations": ["Live Fire Weapons (New Babbage)"],
     "variants": ["Atzkav \"Deadeye\" Sniper", "Atzkav \"Igniter\" Sniper", "Atzkav \"Mirage\" Sniper", "Atzkav \"Venom\" Sniper"]},

    {"id": "scalpel-sniper", "name": "Scalpel Sniper Rifle", "type": "Sniper Rifle", "size": 3, "manufacturer": "Verified Offworld Laser Technologies",
     "damage": 65, "ammo": 8, "fire_rate": "Semi-Auto", "effective_range": "200m",
     "description": "Precision laser sniper. Excellent accuracy at extreme range.",
     "price_auec": 22000,
     "locations": ["Live Fire Weapons (Port Tressler)"],
     "variants": ["Scalpel \"Permafrost\" Sniper"]},

    {"id": "zenith-sniper", "name": "Zenith Laser Sniper Rifle", "type": "Sniper Rifle", "size": 3, "manufacturer": "Lightning Bolt Co.",
     "damage": 50, "ammo": 12, "fire_rate": "Semi-Auto", "effective_range": "190m",
     "description": "Energy sniper with large battery. Multiple faction-branded variants.",
     "price_auec": 20500,
     "locations": ["Live Fire Weapons (Area 18)", "Live Fire Weapons (New Babbage)"],
     "variants": ["Zenith \"Darkwave\" Sniper", "Zenith \"Golden Blossom\" Sniper", "Zenith \"Snow Camo\" Sniper", "Zenith \"Thunderstrike\" Sniper"]},

    # === RAILGUNS ===
    {"id": "scourge-railgun", "name": "Scourge Railgun", "type": "Railgun", "size": 4, "manufacturer": "Kastak Arms",
     "damage": 150, "ammo": 3, "fire_rate": "Charge", "effective_range": "300m",
     "description": "Electromagnetic railgun. Charges before firing. Extreme damage.",
     "price_auec": 14800,
     "locations": ["Grim HEX", "Looted from bunker bosses"],
     "variants": ["Scourge \"Desert Shadow\" Railgun", "Scourge \"Nightstalker\" Railgun", "Scourge \"Quite Useful\" Railgun"]},

    # === GRENADE LAUNCHERS ===
    {"id": "gp33-launcher", "name": "GP-33 MOD Grenade Launcher", "type": "Grenade Launcher", "size": 3, "manufacturer": "Behring",
     "damage": 120, "ammo": 6, "fire_rate": "Semi-Auto", "effective_range": "80m",
     "description": "Six-round grenade launcher. Area denial and group damage.",
     "price_auec": 28500,
     "locations": ["Grim HEX", "Looted from bunker enemies"],
     "variants": ["GP-33 \"Ashfall\" Launcher", "GP-33 \"Copperhead\" Launcher", "GP-33 \"Quite Useful\" Launcher", "GP-33 \"Thunderclap\" Launcher", "GP-33 \"Umber\" Launcher"]},

    # === MISSILE LAUNCHERS ===
    {"id": "animus-launcher", "name": "Animus Missile Launcher", "type": "Missile Launcher", "size": 5, "manufacturer": "Apocalypse Arms",
     "damage": 150, "ammo": 1, "fire_rate": "Single-Shot", "effective_range": "200m",
     "description": "Shoulder-mounted missile launcher. Anti-vehicle capability.",
     "price_auec": 32000,
     "locations": ["Grim HEX", "Rare loot drop"],
     "variants": ["Animus \"Quite Useful\" Launcher"]},

    {"id": "boomtube-launcher", "name": "Boomtube Rocket Launcher", "type": "Missile Launcher", "size": 5, "manufacturer": "Kastak Arms",
     "damage": 180, "ammo": 1, "fire_rate": "Single-Shot", "effective_range": "150m",
     "description": "Unguided rocket launcher. Devastating against vehicles and groups.",
     "price_auec": 28000,
     "locations": ["Grim HEX", "Rare bunker boss loot"],
     "variants": ["Boomtube \"Clanguard\" Launcher", "Boomtube \"Mean Green\" Launcher", "Boomtube \"Ruby\" Launcher"]},

    # === MEDICAL ===
    {"id": "medgun", "name": "MedGun", "type": "Medical Device", "size": 1, "manufacturer": "CureLife",
     "damage": 0, "ammo": 100, "fire_rate": "Continuous", "effective_range": "5m",
     "description": "Medical healing device. Essential for team play.",
     "price_auec": 5500,
     "locations": ["Medical supply vendors (all stations)", "Pharmacy (Orison, New Babbage)"],
     "variants": []},

    {"id": "multitool", "name": "Multi-Tool", "type": "Utility", "size": 1, "manufacturer": "Greycat Industrial",
     "damage": 0, "ammo": 0, "fire_rate": "N/A", "effective_range": "3m",
     "description": "Versatile utility tool. Healing, cutting, tractor beam with attachments.",
     "price_auec": 1200,
     "locations": ["Most station shops", "Cargo Decks"],
     "variants": []},

    # === GRENADES ===
    {"id": "frag-grenade", "name": "Frag Grenade", "type": "Grenade", "size": 0, "manufacturer": "Behring",
     "damage": 200, "ammo": 1, "fire_rate": "Throw", "effective_range": "30m",
     "description": "Standard fragmentation grenade. Lethal in enclosed spaces. 3.5s fuse.",
     "price_auec": 150,
     "locations": ["Live Fire Weapons (most stations)", "Looted from NPCs"],
     "variants": []},

    {"id": "flash-grenade", "name": "Flash Grenade", "type": "Grenade", "size": 0, "manufacturer": "Behring",
     "damage": 0, "ammo": 1, "fire_rate": "Throw", "effective_range": "20m",
     "description": "Flashbang. Blinds and disorients enemies. Essential for breaching.",
     "price_auec": 120,
     "locations": ["Live Fire Weapons (most stations)", "Looted from security NPCs"],
     "variants": []},

    {"id": "smoke-grenade", "name": "Smoke Grenade", "type": "Grenade", "size": 0, "manufacturer": "Behring",
     "damage": 0, "ammo": 1, "fire_rate": "Throw", "effective_range": "25m",
     "description": "Deploys thick smoke screen. Blocks line of sight for 15s.",
     "price_auec": 100,
     "locations": ["Live Fire Weapons (Lorville)", "Live Fire Weapons (Area 18)"],
     "variants": []},

    {"id": "emp-grenade", "name": "EMP Grenade", "type": "Grenade", "size": 0, "manufacturer": "Kastak Arms",
     "damage": 0, "ammo": 1, "fire_rate": "Throw", "effective_range": "15m",
     "description": "Electromagnetic pulse grenade. Disables electronics and shields temporarily.",
     "price_auec": 350,
     "locations": ["Grim HEX", "Rare loot from bunker bosses"],
     "variants": []},

    # === UTILITIES ===
    {"id": "medpen", "name": "MedPen", "type": "Utility", "size": 0, "manufacturer": "CureLife",
     "damage": 0, "ammo": 1, "fire_rate": "Inject", "effective_range": "Self",
     "description": "Emergency medical injector. Heals minor wounds and stops bleeding. Stackable.",
     "price_auec": 100,
     "locations": ["Medical supply vendors (all stations)", "Pharmacy (Orison, New Babbage)", "Looted from NPCs"],
     "variants": ["MedPen Mk II"]},

    {"id": "oxypen", "name": "OxyPen", "type": "Utility", "size": 0, "manufacturer": "CureLife",
     "damage": 0, "ammo": 1, "fire_rate": "Inject", "effective_range": "Self",
     "description": "Oxygen supplement injector. Restores O2 in emergency situations.",
     "price_auec": 75,
     "locations": ["Medical supply vendors (all stations)", "Pharmacy"],
     "variants": []},

    {"id": "adrenapen", "name": "AdrenaPen", "type": "Utility", "size": 0, "manufacturer": "CureLife",
     "damage": 0, "ammo": 1, "fire_rate": "Inject", "effective_range": "Self",
     "description": "Adrenaline injector. Temporarily boosts stamina and reduces pain effects.",
     "price_auec": 200,
     "locations": ["Pharmacy (Orison, New Babbage)", "Medical vendors"],
     "variants": []},

    {"id": "tractor-beam-tool", "name": "Tractor Beam (Multi-Tool)", "type": "Utility", "size": 0, "manufacturer": "Greycat Industrial",
     "damage": 0, "ammo": 0, "fire_rate": "Continuous", "effective_range": "10m",
     "description": "Multi-tool tractor beam attachment. Move cargo boxes and small objects.",
     "price_auec": 1750,
     "locations": ["Cargo Decks (all stations)", "Most station shops"],
     "variants": []},

    {"id": "cutting-tool", "name": "Cutting Tool (Multi-Tool)", "type": "Utility", "size": 0, "manufacturer": "Greycat Industrial",
     "damage": 0, "ammo": 0, "fire_rate": "Continuous", "effective_range": "1m",
     "description": "Multi-tool cutting attachment. Breach locked doors and panels.",
     "price_auec": 1400,
     "locations": ["Cargo Decks (all stations)", "Hardware shops"],
     "variants": []},

    {"id": "repair-tool", "name": "Repair Tool (Multi-Tool)", "type": "Utility", "size": 0, "manufacturer": "Greycat Industrial",
     "damage": 0, "ammo": 0, "fire_rate": "Continuous", "effective_range": "3m",
     "description": "Multi-tool repair attachment. Fix damaged ship components in the field.",
     "price_auec": 1600,
     "locations": ["Cargo Decks (all stations)", "Ship component shops"],
     "variants": []},
]


# PERSONAL ARMOR - base sets with variants (color schemes)
ARMOR_SETS = [
    # === HEAVY ARMOR ===
    {"id": "adp-heavy", "name": "ADP", "type": "Heavy", "manufacturer": "Clark Defense Systems",
     "temp_max": 105, "temp_min": -75, "radiation": 26800,
     "description": "Heavy combat armor. Excellent protection and environmental resistance.",
     "price_auec": 15400,
     "locations": ["Distribution Centers (all)", "Armor shops (Lorville, Area 18)"],
     "loot_locations": ["Bunker missions", "Distribution Centers"],
     "variants": ["ADP Aqua", "ADP Black", "ADP Dark Green", "ADP Grey", "ADP Olive", "ADP Twilight", "ADP Imperial", "ADP Sienna"]},

    {"id": "adp-mk4-heavy", "name": "ADP-mk4", "type": "Heavy", "manufacturer": "Clark Defense Systems",
     "temp_max": 100, "temp_min": -70, "radiation": 26800,
     "description": "Upgraded ADP variant. Found in contested zones. Rare.",
     "price_auec": 18200,
     "locations": ["Pyro One contested zones", "High-security bunkers"],
     "loot_locations": ["Pyro I", "Xenomorph encounter zones"],
     "variants": ["ADP-mk4 Red Alert", "ADP-mk4 Woodland"]},

    {"id": "antium-heavy", "name": "Antium", "type": "Heavy", "manufacturer": "Quirinus Tech",
     "temp_max": 120, "temp_min": -95, "radiation": 26800,
     "description": "Best environmental resistance of all heavy armors. Exploration-grade.",
     "price_auec": 16800,
     "locations": ["Dumper's Depot (New Babbage)", "Armor shops (Orison)"],
     "loot_locations": ["Cave exploration sites"],
     "variants": ["Antium Jet", "Antium Maroon", "Antium Midnight Sun", "Antium Moss Camo", "Antium Sand", "Antium Storm"]},

    {"id": "citadel-heavy", "name": "Citadel", "type": "Heavy", "manufacturer": "Kastak Arms",
     "temp_max": 100, "temp_min": -80, "radiation": 26800,
     "description": "Combat-focused heavy armor. Distinctive angular design.",
     "price_auec": 19500,
     "locations": ["ASD Facilities (Pyro)", "Crusader Security loot"],
     "loot_locations": ["ASD Facilities", "Security bunkers"],
     "variants": ["Citadel Brimstone", "Citadel Dark Red", "Citadel Earthwork", "Citadel Icefall", "Citadel Ignitor", "Citadel Outcrop", "Citadel Roughshod"]},

    {"id": "corbel-heavy", "name": "Corbel", "type": "Heavy", "manufacturer": "Odin Munitions",
     "temp_max": 100, "temp_min": -70, "radiation": 26800,
     "description": "Rugged heavy armor designed for sustained ground operations.",
     "price_auec": 17600,
     "locations": ["Armor shops (Lorville)", "Distribution Centers"],
     "loot_locations": ["Ground bunker missions"],
     "variants": ["Corbel Crush", "Corbel Halcyon", "Corbel Mire", "Corbel Patina", "Corbel Smolder"]},

    {"id": "defiance-heavy", "name": "Defiance", "type": "Heavy", "manufacturer": "Clark Defense Systems",
     "temp_max": 102, "temp_min": -72, "radiation": 26800,
     "description": "Premium heavy armor with enhanced protection.",
     "price_auec": 20200,
     "locations": ["Subscriber rewards", "Rare loot"],
     "loot_locations": ["High-threat bunkers"],
     "variants": ["Defiance Charcoal", "Defiance Desert", "Defiance Firestarter", "Defiance Hailstorm", "Defiance Scorched", "Defiance Sunchaser", "Defiance Tactical"]},

    {"id": "morozov-sh-heavy", "name": "Morozov-SH", "type": "Heavy", "manufacturer": "Roussimoff",
     "temp_max": 105, "temp_min": -75, "radiation": 26800,
     "description": "Crusader Security heavy armor. Distinct blue/white markings.",
     "price_auec": 12800,
     "locations": ["ASD Facilities", "Looted from Crusader Security NPCs"],
     "loot_locations": ["ASD Facilities", "Crusader security zones"],
     "variants": ["Morozov-SH Aftershock", "Morozov-SH Brushdrift", "Morozov-SH Crusader Edition", "Morozov-SH Redshift", "Morozov-SH Snowdrift", "Morozov-SH Terracotta", "Morozov-SH Thule"]},

    {"id": "overlord-heavy", "name": "Overlord", "type": "Heavy", "manufacturer": "Doomsday",
     "temp_max": 100, "temp_min": -70, "radiation": 26800,
     "description": "Intimidating heavy armor with skull motif. Popular with outlaws.",
     "price_auec": 13500,
     "locations": ["Grim HEX", "Subscription exclusive variants"],
     "loot_locations": ["Outlaw bunkers"],
     "variants": ["Overlord Dust Storm", "Overlord Predator", "Overlord Riptide", "Overlord Stinger", "Overlord Supernova", "Overlord Switchback"]},

    {"id": "palatino-heavy", "name": "Palatino", "type": "Heavy", "manufacturer": "Quirinus Tech",
     "temp_max": 100, "temp_min": -70, "radiation": 26800,
     "description": "Widely available heavy armor. Found at all distribution centers.",
     "price_auec": 11200,
     "locations": ["All Distribution Centers", "Armor shops (all landing zones)"],
     "loot_locations": ["Distribution Centers"],
     "variants": ["Palatino Daystar", "Palatino Deadlock", "Palatino Mark I", "Palatino Metropolis", "Palatino Moonfall", "Palatino Necropolis", "Palatino Shadow Gild", "Palatino Sunstone"]},

    # === MEDIUM ARMOR ===
    {"id": "artimex-medium", "name": "Artimex", "type": "Medium", "manufacturer": "Clark Defense Systems",
     "temp_max": 85, "temp_min": -55, "radiation": 26400,
     "description": "Balanced medium armor. Good mix of protection and mobility.",
     "price_auec": 14200,
     "locations": ["Armor shops (most stations)", "Distribution Centers"],
     "loot_locations": ["Bunker missions"],
     "variants": ["Artimex Canuto", "Artimex Lodestone", "Artimex Red Alert", "Artimex Wildwood"]},

    {"id": "aril-medium", "name": "Aril", "type": "Medium", "manufacturer": "Quirinus Tech",
     "temp_max": 88, "temp_min": -58, "radiation": 26400,
     "description": "Medium exploration armor with good environmental protection.",
     "price_auec": 8400,
     "locations": ["Dumper's Depot (New Babbage)", "Cargo Decks (most stations)"],
     "loot_locations": ["Mining outposts"],
     "variants": ["Aril Black Cherry", "Aril Harvester", "Aril Hazard", "Aril Quicksilver", "Aril Red Alert"]},

    {"id": "aves-medium", "name": "Aves", "type": "Medium", "manufacturer": "Kastak Arms",
     "temp_max": 82, "temp_min": -52, "radiation": 26400,
     "description": "Combat-oriented medium armor. Favored by bounty hunters.",
     "price_auec": 9200,
     "locations": ["Armor shops (Lorville)", "Grim HEX"],
     "loot_locations": ["Bounty hunt targets"],
     "variants": ["Aves Epoque"]},

    {"id": "novikov-medium", "name": "Novikov", "type": "Medium", "manufacturer": "Odin Munitions",
     "temp_max": 95, "temp_min": -65, "radiation": 26400,
     "description": "Exploration suit with excellent cold protection. Popular for microTech.",
     "price_auec": 10600,
     "locations": ["Hatter Station", "New Babbage shops"],
     "loot_locations": ["microTech surface missions"],
     "variants": ["Novikov Amber", "Novikov Polar", "Novikov Ember", "Novikov Storm"]},

    {"id": "lynx-medium", "name": "Lynx", "type": "Medium", "manufacturer": "Behring",
     "temp_max": 80, "temp_min": -50, "radiation": 26400,
     "description": "Tactical medium armor. Good for all-around combat operations.",
     "price_auec": 7800,
     "locations": ["Armor shops (most stations)"],
     "loot_locations": ["General NPC loot"],
     "variants": ["Lynx Blue", "Lynx Draas", "Lynx Firebrick", "Lynx Lichen", "Lynx Olive", "Lynx Orange", "Lynx Sandstorm", "Lynx Seagreen"]},

    # === LIGHT ARMOR ===
    {"id": "arden-sl-light", "name": "Arden-SL", "type": "Light", "manufacturer": "Roussimoff",
     "temp_max": 68, "temp_min": -38, "radiation": 26800,
     "description": "Light security armor. Minimal protection, maximum mobility.",
     "price_auec": 8800,
     "locations": ["Armor shops (most stations)", "Cargo Decks"],
     "loot_locations": ["Security NPC drops"],
     "variants": ["Arden-SL Archangel", "Arden-SL Balefire", "Arden-SL Red Alert", "Arden-SL Rime"]},

    {"id": "aztalan-light", "name": "Aztalan", "type": "Light", "manufacturer": "Tehachapi",
     "temp_max": 68, "temp_min": -38, "radiation": 26000,
     "description": "Lightweight stealth-oriented armor. Low profile design.",
     "price_auec": 6200,
     "locations": ["Armor shops (Area 18)", "Grim HEX"],
     "loot_locations": ["Outlaw bunkers"],
     "variants": ["Aztalan Night", "Aztalan Desert", "Aztalan Ember", "Aztalan Frost"]},

    {"id": "calico-light", "name": "Calico", "type": "Light", "manufacturer": "Kastak Arms",
     "temp_max": 69, "temp_min": -39, "radiation": 26000,
     "description": "Agile light combat armor. Designed for fast-movers.",
     "price_auec": 5800,
     "locations": ["Armor shops (Lorville)", "Live Fire Weapons"],
     "loot_locations": ["Ground combat zones"],
     "variants": ["Calico Desert", "Calico Tactical"]},

    {"id": "fbl-8a-light", "name": "FBL-8a", "type": "Light", "manufacturer": "Clark Defense Systems",
     "temp_max": 65, "temp_min": -35, "radiation": 26000,
     "description": "Standard light combat armor. Widely available and affordable.",
     "price_auec": 6800,
     "locations": ["Armor shops (all landing zones)"],
     "loot_locations": ["General NPC drops"],
     "variants": ["FBL-8a Arctic Digital", "FBL-8a Desert Digital", "FBL-8a Imperial Red"]},

    {"id": "sterling-light", "name": "Sterling", "type": "Light", "manufacturer": "Quirinus Tech",
     "temp_max": 70, "temp_min": -40, "radiation": 26000,
     "description": "Exploration light armor. Better environmental stats than most light sets.",
     "price_auec": 9800,
     "locations": ["Pyro One", "Larger loot locations"],
     "loot_locations": ["Pyro I facilities", "Exploration sites"],
     "variants": ["Sterling Explorer", "Sterling Ranger", "Sterling Shadow", "Sterling Frost"]},

    # === ADDITIONAL MISSING SETS ===
    {"id": "orc-mkx-medium", "name": "ORC-mkX", "type": "Medium", "manufacturer": "Clark Defense Systems",
     "temp_max": 91, "temp_min": -61, "radiation": 26400,
     "description": "Medium combat armor used by Protector Marines. Successor to ORC-mkV. 30% damage reduction. EVA-rated.",
     "price_auec": 3200,
     "locations": ["Galleria FPS Armor (Jump Points)", "MIC-L4", "Area 18 Armor shops"],
     "loot_locations": ["Bunker missions", "Distribution Centers"],
     "variants": ["ORC-mkX Desert", "ORC-mkX Iceborn", "ORC-mkX Nightfire", "ORC-mkX Woodland", "ORC-mkX Singularity", "ORC-mkX Arctic", "ORC-mkX Autumn", "ORC-mkX Twilight"]},

    {"id": "orc-mkv-medium", "name": "ORC-mkV", "type": "Medium", "manufacturer": "Clark Defense Systems",
     "temp_max": 85, "temp_min": -55, "radiation": 26400,
     "description": "Predecessor to the ORC-mkX. Reliable medium combat armor still widely found in the verse.",
     "price_auec": 2800,
     "locations": ["Armor shops (Hurston)", "Distribution Centers"],
     "loot_locations": ["Bunker missions", "Security NPC drops"],
     "variants": ["ORC-mkV Aqua", "ORC-mkV Black", "ORC-mkV Blue", "ORC-mkV Dark Green", "ORC-mkV Dark Red", "ORC-mkV Grey", "ORC-mkV Orange", "ORC-mkV Scorched", "ORC-mkV Twilight"]},

    {"id": "macflex-medium", "name": "MacFlex", "type": "Medium", "manufacturer": "Clark Defense Systems",
     "temp_max": 82, "temp_min": -52, "radiation": 26400,
     "description": "Flex-weave medium armor with excellent mobility. Common civilian and security armor.",
     "price_auec": 4200,
     "locations": ["Armor shops (most stations)", "Cargo Decks"],
     "loot_locations": ["Distribution Centers", "General NPC drops"],
     "variants": ["MacFlex Black", "MacFlex Aqua", "MacFlex Blue", "MacFlex Dark Green", "MacFlex Dark Red", "MacFlex Grey", "MacFlex Imperial", "MacFlex Olive", "MacFlex Orange"]},

    {"id": "venture-light", "name": "Venture", "type": "Light", "manufacturer": "RSI",
     "temp_max": 70, "temp_min": -40, "radiation": 26000,
     "description": "RSI light exploration armor. Space-optimized with glass cockpit HUD integration.",
     "price_auec": 7200,
     "locations": ["Clothing shops (most stations)", "Dumper's Depot"],
     "loot_locations": [],
     "variants": ["Venture Black", "Venture Aqua", "Venture Blue", "Venture Dark Green", "Venture Grey", "Venture Executive", "Venture Ascension", "Venture Envy", "Venture Lovestruck"]},

    {"id": "inquisitor-medium", "name": "Inquisitor", "type": "Medium", "manufacturer": "Kastak Arms",
     "temp_max": 88, "temp_min": -58, "radiation": 26400,
     "description": "Enforcement-grade medium armor. Distinctive angular visor design. Favored by bounty hunters.",
     "price_auec": 11500,
     "locations": ["Grim HEX", "Armor shops (Lorville)"],
     "loot_locations": ["Bunker missions", "Nine Tails enemy drops"],
     "variants": ["Inquisitor Black Steel", "Inquisitor Neon Pink", "Inquisitor Raven"]},

    {"id": "truedef-pro-light", "name": "TrueDef-Pro", "type": "Light", "manufacturer": "Virgil Ltd",
     "temp_max": 65, "temp_min": -35, "radiation": 26000,
     "description": "Law enforcement light armor. 20% damage reduction. Used by Advocacy and CDF personnel.",
     "price_auec": 5500,
     "locations": ["Armor shops (most stations)", "Security facilities"],
     "loot_locations": ["Security NPC drops", "Advocacy missions"],
     "variants": ["TrueDef-Pro Red/Silver", "TrueDef-Pro Black/Grey", "TrueDef-Pro Black/Grey/Red", "TrueDef-Pro CDF", "TrueDef-Pro Black/Silver/Green", "TrueDef-Pro Aqua/Black"]},

    {"id": "pab1-light", "name": "PAB-1", "type": "Light", "manufacturer": "Clark Defense Systems",
     "temp_max": 65, "temp_min": -35, "radiation": 26000,
     "description": "Police and security light armor. Minimal protection with high visibility markings.",
     "price_auec": 4800,
     "locations": ["Armor shops (all landing zones)", "Security outfitters"],
     "loot_locations": ["Security NPC drops", "Crusader Security zones"],
     "variants": ["PAB-1 Black", "PAB-1 Aqua", "PAB-1 Blue", "PAB-1 Desert", "PAB-1 Red", "PAB-1 Crusader Edition", "PAB-1 Imperial"]},

    # === FLIGHT SUITS ===
    {"id": "odyssey-ii-flight", "name": "Odyssey II", "type": "Flight Suit", "manufacturer": "RSI",
     "temp_max": 70, "temp_min": -40, "radiation": 15200,
     "description": "Standard RSI flight suit. Starter equipment for most pilots.",
     "price_auec": 14800,
     "locations": ["All station clothing shops", "Default starter gear"],
     "loot_locations": [],
     "variants": ["Odyssey II Red", "Odyssey II Blue", "Odyssey II Black", "Odyssey II White", "Odyssey II Gold"]},

    {"id": "sol-iii-flight", "name": "Sol-III", "type": "Flight Suit", "manufacturer": "UEE Navy",
     "temp_max": 60, "temp_min": -30, "radiation": 15200,
     "description": "Military flight suit. UEE Navy standard issue.",
     "price_auec": 10200,
     "locations": ["Military surplus shops", "Looted from UEE Navy NPCs"],
     "loot_locations": ["UEE naval vessels"],
     "variants": ["Sol-III Aviator", "Sol-III Bombardier"]},

    # === ADDITIONAL HEAVY ARMOR (CStone) ===
    {"id": "ana-heavy", "name": "Ana", "type": "Heavy", "manufacturer": "Quirinus Tech",
     "temp_max": 120, "temp_min": -95, "radiation": 26800,
     "description": "Top-tier heavy armor with maximum environmental resistance. Loot only. 40% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["High-security Pyro facilities", "Contested zone loot crates", "Boss NPC drops"],
     "variants": ["Ana Endro", "Ana Wao"]},

    {"id": "bokto-heavy", "name": "Bokto", "type": "Heavy", "manufacturer": "Quirinus Tech",
     "temp_max": 120, "temp_min": -95, "radiation": 27202,
     "description": "Extremely rare heavy armor. Highest radiation resistance among all heavy sets. Loot only.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Pyro contested facilities", "Rare bunker boss drops", "High-threat operations"],
     "variants": []},

    {"id": "citadel-se-heavy", "name": "Citadel-SE", "type": "Heavy", "manufacturer": "Kastak Arms",
     "temp_max": 110, "temp_min": -80, "radiation": 26800,
     "description": "Special Edition Citadel. Enhanced heavy combat armor. Loot only. 40% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["ASD Facilities (Pyro)", "Crusader Security operations", "Contested zone crates"],
     "variants": ["Citadel-SE Dark Green", "Citadel-SE Maroon", "Citadel-SE White"]},

    {"id": "dcp-armor-heavy", "name": "DCP Armor", "type": "Heavy", "manufacturer": "Clark Defense Systems",
     "temp_max": 100, "temp_min": -70, "radiation": 26800,
     "description": "Clark Defense heavy combat platform. Military-grade protection. Loot only. 40% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Military bunker raids", "Security facility loot racks", "Pyro contested zones"],
     "variants": ["DCP Armor Clawed Steel", "DCP Armor Cobalt Camo", "DCP Armor Hunter Camo", "DCP Armor Jungle Camo", "DCP Armor New Dawn", "DCP Armor True Valor"]},

    {"id": "dust-devil-heavy", "name": "Dust Devil", "type": "Heavy", "manufacturer": "Unknown",
     "temp_max": 115, "temp_min": -85, "radiation": 26800,
     "description": "Rare heavy armor found in frontier areas. Loot only. 40% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Desert planet outpost loot", "Hurston surface missions", "Rare outlaw NPC drops"],
     "variants": ["Dust Devil Epoque"]},

    {"id": "dust-devil-armor-heavy", "name": "Dust Devil Armor", "type": "Heavy", "manufacturer": "Unknown",
     "temp_max": 115, "temp_min": -85, "radiation": 26800,
     "description": "Variant of Dust Devil with full combat plating. Loot only. 40% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["High-threat bunker raids", "Frontier outpost crates", "Pyro facility loot"],
     "variants": []},

    {"id": "morozov-sh-i-heavy", "name": "Morozov-SH-I", "type": "Heavy", "manufacturer": "Roussimoff Rehabilitation Systems",
     "temp_max": 105, "temp_min": -75, "radiation": 26800,
     "description": "Advanced Morozov variant. Military-grade Crusader armor. Loot only. 40% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Crusader military operations", "ASD Facility raids", "Crusader patrol interdictions"],
     "variants": ["Morozov-SH-I Gideon", "Morozov-SH-I Lifeforce", "Morozov-SH-I Pyrotechnic", "Morozov-SH-I Pyrotechnic Horizon"]},

    {"id": "wrecker-heavy", "name": "Wrecker", "type": "Heavy", "manufacturer": "Unknown",
     "temp_max": 100, "temp_min": -70, "radiation": 26800,
     "description": "Salvage-themed heavy armor. Loot only. 40% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Salvage operation sites", "Derelict ship loot", "Contested zone crates"],
     "variants": ["Wrecker Ashen", "Wrecker Payback"]},

    # === ADDITIONAL MEDIUM ARMOR (CStone) ===
    {"id": "aves-shrike-medium", "name": "Aves Shrike", "type": "Medium", "manufacturer": "CC's Conversions",
     "temp_max": 91, "temp_min": -61, "radiation": 26400,
     "description": "Aves variant with aggressive styling. Loot only. 30% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Bounty hunter target drops", "Outlaw bunker missions", "Grim HEX area loot"],
     "variants": []},

    {"id": "aves-starchaser-medium", "name": "Aves Starchaser", "type": "Medium", "manufacturer": "CC's Conversions",
     "temp_max": 91, "temp_min": -61, "radiation": 26400,
     "description": "Exploration-themed Aves variant. Loot only. 30% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Exploration sites", "Frontier outpost loot", "Derelict ship crates"],
     "variants": []},

    {"id": "aves-talon-medium", "name": "Aves Talon", "type": "Medium", "manufacturer": "CC's Conversions",
     "temp_max": 91, "temp_min": -61, "radiation": 26400,
     "description": "Combat-focused Aves variant. Loot only. 30% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["High-threat bounty targets", "Outlaw NPC drops", "Contested zone loot"],
     "variants": []},

    {"id": "carrion-medium", "name": "Carrion", "type": "Medium", "manufacturer": "Unknown",
     "temp_max": 80, "temp_min": -50, "radiation": 26400,
     "description": "Scavenger-themed medium armor. Multiple camo variants. Loot only. 30% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Salvage operation sites", "Derelict ship crates", "Outlaw bunker loot"],
     "variants": ["Carrion Ashen", "Carrion Maniac", "Carrion Payback", "Carrion Stalker"]},

    {"id": "clash-medium", "name": "Clash", "type": "Medium", "manufacturer": "Doomsday",
     "temp_max": 82, "temp_min": -52, "radiation": 26400,
     "description": "Aggressive medium combat armor by Doomsday. Loot only. 30% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Outlaw bunker missions", "Nine Tails NPC drops", "Grim HEX area loot"],
     "variants": []},

    {"id": "dustup-medium", "name": "DustUp", "type": "Medium", "manufacturer": "Kastak Arms",
     "temp_max": 90, "temp_min": -60, "radiation": 26400,
     "description": "Versatile medium armor by Kastak Arms. Some variants purchasable. 30% damage reduction.",
     "price_auec": 8500,
     "locations": ["Armor shops (Lorville)", "Live Fire Weapons"],
     "loot_locations": ["Bunker missions", "Distribution Centers"],
     "variants": ["DustUp Desert", "DustUp Firestarter", "DustUp Scorched", "DustUp Tactical"]},

    {"id": "gcd-army-medium", "name": "GCD-Army", "type": "Medium", "manufacturer": "Clark Defense Systems",
     "temp_max": 91, "temp_min": -61, "radiation": 26400,
     "description": "Military-grade medium combat armor. Army issue. Loot only. 30% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Military bunker raids", "Army NPC drops", "Restricted military zones"],
     "variants": []},

    {"id": "stitcher-medium", "name": "Stitcher", "type": "Medium", "manufacturer": "Doomsday",
     "temp_max": 82, "temp_min": -52, "radiation": 26400,
     "description": "Industrial medium armor by Doomsday. Available at select vendors. 30% damage reduction.",
     "price_auec": 7200,
     "locations": ["Grim HEX armor shop", "Pyro outpost vendors"],
     "loot_locations": ["Outlaw bunker missions"],
     "variants": []},

    {"id": "strata-medium", "name": "Strata", "type": "Medium", "manufacturer": "Greycat Industrial",
     "temp_max": 91, "temp_min": -61, "radiation": 26400,
     "description": "Greycat Industrial medium armor with many faction variants. 15k uSCU carrying capacity. 30% damage reduction.",
     "price_auec": 9200,
     "locations": ["Armor shops (most stations)", "Greycat showrooms"],
     "loot_locations": ["Distribution Centers", "Faction facility loot"],
     "variants": ["Strata ArcCorp Black", "Strata ArcCorp Edition", "Strata Crusader Black", "Strata Crusader Edition", "Strata Greycat Edition", "Strata Heatwave", "Strata Hurston Black", "Strata Hurston Edition", "Strata microTech Black", "Strata microTech Edition", "Strata Pyrotechnic Edition", "Strata Shubin Edition"]},

    {"id": "testudo-medium", "name": "Testudo", "type": "Medium", "manufacturer": "Quirinus Tech",
     "temp_max": 80, "temp_min": -50, "radiation": 26400,
     "description": "Defensive medium armor inspired by the tortoise formation. Loot only. 30% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Ground defense operations", "Bunker loot crates", "Security facility racks"],
     "variants": ["Testudo Clanguard", "Testudo Combustion", "Testudo Deathblow", "Testudo Disrupt Camo", "Testudo Earthshake", "Testudo Nightveil", "Testudo Turfwar"]},

    # === ADDITIONAL LIGHT ARMOR (CStone) ===
    {"id": "aztalan-galena-light", "name": "Aztalan Galena", "type": "Light", "manufacturer": "Tehachapi",
     "temp_max": 65, "temp_min": -35, "radiation": 26000,
     "description": "Mineral-themed Aztalan variant. Loot only. 20% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Mining outpost loot", "Frontier exploration sites", "Cave loot crates"],
     "variants": []},

    {"id": "aztalan-tamarack-light", "name": "Aztalan Tamarack", "type": "Light", "manufacturer": "Tehachapi",
     "temp_max": 65, "temp_min": -35, "radiation": 26000,
     "description": "Forest-themed Aztalan variant. Loot only. 20% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Woodland planet surface loot", "Outpost beige boxes", "Bunker weapon racks"],
     "variants": []},

    {"id": "carnifex-light", "name": "Carnifex", "type": "Light", "manufacturer": "Gyson Inc.",
     "temp_max": 38, "temp_min": -5, "radiation": 26000,
     "description": "Minimal protection stealth armor. Very low environmental tolerance. Loot only. 20% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Stealth operation sites", "Rare outlaw NPC drops", "Covert facility loot"],
     "variants": ["Carnifex Windfall"]},

    {"id": "carnifex-armor-light", "name": "Carnifex Armor", "type": "Light", "manufacturer": "Gyson Inc.",
     "temp_max": 38, "temp_min": -5, "radiation": 26000,
     "description": "Armored Carnifex variant. Minimal environmental tolerance. Loot only. 20% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["High-threat stealth missions", "Outlaw boss drops", "Pyro covert facilities"],
     "variants": ["Carnifex Armor Brassy", "Carnifex Armor Bruiser", "Carnifex Armor Shutdown"]},

    {"id": "chiron-light", "name": "Chiron", "type": "Light", "manufacturer": "Virgil",
     "temp_max": 62, "temp_min": -32, "radiation": 26000,
     "description": "Medical-themed light armor. Loot only. 20% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Medical facility loot", "Hospital beige boxes", "Medic NPC drops"],
     "variants": ["Chiron AA Support", "Chiron Heartthrob"]},

    {"id": "field-recon-suit-light", "name": "Field Recon Suit", "type": "Light", "manufacturer": "Clark Defense Systems",
     "temp_max": 62, "temp_min": -32, "radiation": 26000,
     "description": "Lightweight recon armor. Designed for scouting operations. Purchasable. 20% damage reduction.",
     "price_auec": 6800,
     "locations": ["Armor shops (Port Tressler)", "Military surplus vendors"],
     "loot_locations": ["Recon NPC drops", "Military outpost loot"],
     "variants": []},

    {"id": "geist-armor-light", "name": "Geist Armor", "type": "Light", "manufacturer": "Kilgore and Poole",
     "temp_max": 65, "temp_min": -35, "radiation": 26000,
     "description": "Distinctive light armor with many rare variants. Loot only. 20% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["High-value target missions", "Rare NPC drops", "Pyro contested zones"],
     "variants": ["Geist Armor ASD Edition", "Geist Armor Desert", "Geist Armor Epoque", "Geist Armor Forest", "Geist Armor Golden Blossom", "Geist Armor Rogue", "Geist Armor Snow Camo", "Geist Armor Whiteout"]},

    {"id": "microid-battle-suit-light", "name": "Microid Battle Suit", "type": "Light", "manufacturer": "Kastak Arms",
     "temp_max": 63, "temp_min": -33, "radiation": 26000,
     "description": "Compact battle suit. Most variants purchasable. 20% damage reduction.",
     "price_auec": 5500,
     "locations": ["Armor shops (Area 18)", "Armor shops (Lorville)", "Casaba Outlet"],
     "loot_locations": ["General NPC drops"],
     "variants": ["Microid Battle Suit Badland", "Microid Battle Suit Crucible", "Microid Battle Suit Lodestone", "Microid Battle Suit Lowland", "Microid Battle Suit Nomad"]},

    {"id": "piecemeal-armor-light", "name": "Piecemeal Armor", "type": "Light", "manufacturer": "Unknown",
     "temp_max": 61, "temp_min": -31, "radiation": 26000,
     "description": "Cobbled-together light armor from salvaged parts. Loot only. 20% damage reduction.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Salvage sites", "Derelict ship crates", "Scrapyard outpost loot"],
     "variants": ["Piecemeal Armor Grey", "Piecemeal Armor Olive"]},

    # === BACKPACKS (from CStone - part of Armor sets) ===
    {"id": "arden-cl-backpack", "name": "Arden-CL Backpack", "type": "Backpack", "manufacturer": "Roussimoff Rehabilitation Systems",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Light backpack. 40K uSCU carrying capacity. Compatible with all armor cores.",
     "price_auec": 2800,
     "locations": ["Armor shops (most stations)", "Cargo Decks"],
     "loot_locations": ["Security NPC drops"],
     "variants": ["Arden-CL Backpack Archangel", "Arden-CL Backpack Balefire", "Arden-CL Backpack Chairman's Club", "Arden-CL Backpack Elysium", "Arden-CL Backpack Red Alert", "Arden-CL Backpack Rime"]},

    {"id": "aril-backpack", "name": "Aril Backpack", "type": "Backpack", "manufacturer": "Greycat Industrial",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Medium backpack. 85K uSCU carrying capacity. Compatible with medium and heavy cores.",
     "price_auec": 4200,
     "locations": ["Dumper's Depot (New Babbage)", "Cargo Decks"],
     "loot_locations": ["Mining outpost loot"],
     "variants": ["Aril Backpack Black Cherry", "Aril Backpack Harvester", "Aril Backpack Hazard", "Aril Backpack Quicksilver", "Aril Backpack Red Alert (IAE 2952)"]},

    {"id": "cataby-backpack", "name": "Cataby Backpack", "type": "Backpack", "manufacturer": "Hardin Tactical",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Light backpack. 75K uSCU carrying capacity. Compatible with all armor cores.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Rare NPC drops", "Special event loot"],
     "variants": ["Cataby Backpack Lifeforce Edition", "Cataby Backpack MPUV-1C Edition"]},

    {"id": "chiron-backpack", "name": "Chiron Backpack", "type": "Backpack", "manufacturer": "Virgil",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Light backpack. 75K uSCU carrying capacity. Pairs with Chiron armor set.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Medical facility loot", "Medic NPC drops"],
     "variants": ["Chiron Backpack Heartthrob"]},

    {"id": "csp-68h-backpack", "name": "CSP-68H Backpack", "type": "Backpack", "manufacturer": "Clark Defense Systems",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy backpack. 150K uSCU carrying capacity. Compatible with heavy cores only.",
     "price_auec": 6800,
     "locations": ["Armor shops (Lorville)", "Military surplus vendors"],
     "loot_locations": ["Military bunker loot"],
     "variants": ["CSP-68H Backpack Red Alert"]},

    {"id": "csp-68l-backpack", "name": "CSP-68L Backpack", "type": "Backpack", "manufacturer": "Clark Defense Systems",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Light backpack. 54K uSCU carrying capacity. Compatible with all armor cores.",
     "price_auec": 2400,
     "locations": ["Armor shops (most stations)"],
     "loot_locations": ["General NPC drops"],
     "variants": ["CSP-68L Backpack Cayman", "CSP-68L Backpack Epoque", "CSP-68L Backpack Forest Camo", "CSP-68L Backpack Night Camo"]},

    {"id": "csp-68m-backpack", "name": "CSP-68M Backpack", "type": "Backpack", "manufacturer": "Clark Defense Systems",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Medium backpack. 70K uSCU carrying capacity. Compatible with medium and heavy cores.",
     "price_auec": 3600,
     "locations": ["Armor shops (most stations)"],
     "loot_locations": ["Bunker missions"],
     "variants": ["CSP-68M Backpack Epoque"]},

    {"id": "gcd-army-backpack", "name": "GCD-Army Backpack", "type": "Backpack", "manufacturer": "Clark Defense Systems",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Medium military backpack. 105K uSCU carrying capacity. Loot only.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Military bunker raids", "Army NPC drops"],
     "variants": []},

    {"id": "geist-backpack", "name": "Geist Backpack", "type": "Backpack", "manufacturer": "Clark Defense Systems",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Light backpack. 54K uSCU carrying capacity. Pairs with Geist Armor set.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["High-value target missions", "Rare NPC drops"],
     "variants": ["Geist Backpack ASD Edition", "Geist Backpack Desert", "Geist Backpack Forest", "Geist Backpack Golden Blossom", "Geist Backpack Rogue", "Geist Backpack Snow Camo", "Geist Backpack Whiteout"]},

    {"id": "macflex-backpack", "name": "MacFlex Backpack", "type": "Backpack", "manufacturer": "Roberts Space Industries",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Light backpack. 50K uSCU carrying capacity. Compatible with all armor cores.",
     "price_auec": 2400,
     "locations": ["Armor shops (most stations)", "Cargo Decks"],
     "loot_locations": [],
     "variants": ["MacFlex Backpack Canary Yellow", "MacFlex Backpack Granite Red", "MacFlex Backpack Grey", "MacFlex Backpack Orange", "MacFlex Backpack White"]},

    {"id": "macflex-rucksack-backpack", "name": "MacFlex \"Rucksack\" Backpack", "type": "Backpack", "manufacturer": "Roberts Space Industries",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Light rucksack variant. 50K uSCU carrying capacity.",
     "price_auec": 2200,
     "locations": ["Clothing shops", "Dumper's Depot"],
     "loot_locations": [],
     "variants": []},

    {"id": "morozov-ch-backpack", "name": "Morozov-CH Backpack", "type": "Backpack", "manufacturer": "Roussimoff Rehabilitation Systems",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy backpack. 150K uSCU carrying capacity. Pairs with Morozov armor sets.",
     "price_auec": 5800,
     "locations": ["ASD Facilities", "Crusader armor shops"],
     "loot_locations": ["Crusader Security NPC drops"],
     "variants": ["Morozov-CH Backpack Aftershock", "Morozov-CH Backpack Brushdrift", "Morozov-CH Backpack Crusader Edition", "Morozov-CH Backpack Lifeforce", "Morozov-CH Backpack Pyrotechnic", "Morozov-CH Backpack Pyrotechnic Horizon", "Morozov-CH Backpack Red Alert", "Morozov-CH Backpack Redshift", "Morozov-CH Backpack Snowdrift", "Morozov-CH Backpack Terracotta", "Morozov-CH Backpack Thule"]},

    {"id": "morozov-sh-i-backpack", "name": "Morozov-SH-I Backpack", "type": "Backpack", "manufacturer": "Roussimoff Rehabilitation Systems",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy military backpack. 150K uSCU carrying capacity. Loot only.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Crusader military operations", "ASD Facility raids"],
     "variants": ["Morozov-SH-I Backpack Gideon"]},

    {"id": "novikov-backpack", "name": "Novikov Backpack", "type": "Backpack", "manufacturer": "Caldera",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy exploration backpack. 180K uSCU carrying capacity. Pairs with Novikov armor.",
     "price_auec": 4200,
     "locations": ["Hatter Station (microTech)", "New Babbage shops"],
     "loot_locations": ["microTech surface missions"],
     "variants": ["Novikov Backpack Crush", "Novikov Backpack Halcyon", "Novikov Backpack Mire", "Novikov Backpack Patina", "Novikov Backpack Smolder"]},

    {"id": "novikov-ascension-backpack", "name": "Novikov \"Ascension\" Backpack", "type": "Backpack", "manufacturer": "Caldera",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy exploration backpack. 180K uSCU. Event exclusive variant.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Event exclusive / Limited time availability"],
     "variants": []},

    {"id": "novikov-expo-backpack", "name": "Novikov \"Expo\" Backpack", "type": "Backpack", "manufacturer": "Caldera",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy exploration backpack. 180K uSCU. Expo exclusive variant.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["IAE Expo exclusive"],
     "variants": []},

    {"id": "palatino-backpack", "name": "Palatino Backpack", "type": "Backpack", "manufacturer": "Quirinus Tech",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy backpack. 180K uSCU carrying capacity. Pairs with Palatino armor.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Rare bunker drops", "High-value target missions"],
     "variants": ["Palatino Backpack Daystar", "Palatino Backpack Deadlock", "Palatino Backpack Mark I", "Palatino Backpack Metropolis", "Palatino Backpack Moonfall", "Palatino Backpack Necropolis", "Palatino Backpack Shadow Gild", "Palatino Backpack Sunstone"]},

    {"id": "pembroke-backpack", "name": "Pembroke Backpack", "type": "Backpack", "manufacturer": "Caldera",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy exploration backpack. 180K uSCU carrying capacity. Pairs with Pembroke armor.",
     "price_auec": 3600,
     "locations": ["Cargo Decks (most stations)", "Dumper's Depot"],
     "loot_locations": ["Extreme-environment outpost loot"],
     "variants": ["Pembroke Backpack RSI Graphite Edition", "Pembroke Backpack RSI Ivory Edition", "Pembroke Backpack RSI Sunburst Edition"]},

    {"id": "sinkhole-backpack", "name": "Sinkhole Backpack", "type": "Backpack", "manufacturer": "Doomsday",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Medium backpack. 70K uSCU carrying capacity. Industrial design.",
     "price_auec": 3200,
     "locations": ["Grim HEX armor shop"],
     "loot_locations": ["Outlaw bunker loot"],
     "variants": []},

    {"id": "stirling-exploration-backpack", "name": "Stirling Exploration Backpack", "type": "Backpack", "manufacturer": "Roberts Space Industries",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy exploration backpack. 180K uSCU carrying capacity. Many faction variants.",
     "price_auec": 5200,
     "locations": ["Pyro outpost vendors", "Explorer gear shops"],
     "loot_locations": ["Exploration sites", "Frontier outpost loot"],
     "variants": ["Stirling Exploration Backpack Alkaline Edition", "Stirling Exploration Backpack ASD Edition", "Stirling Exploration Backpack Chroma Edition", "Stirling Exploration Backpack Granite Edition", "Stirling Exploration Backpack Olympian Edition", "Stirling Exploration Backpack Sandstorm Edition", "Stirling Exploration Backpack Sediment Edition", "Stirling Exploration Backpack Transistor Edition", "Stirling Exploration Backpack Tungsten Edition"]},

    {"id": "stirling-hazard-backpack", "name": "Stirling Hazard Backpack", "type": "Backpack", "manufacturer": "Roberts Space Industries",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy hazard backpack. 180K uSCU. Designed for hazardous environments.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Hazardous zone outpost loot", "Mining facility crates"],
     "variants": []},

    {"id": "strata-backpack", "name": "Strata Backpack", "type": "Backpack", "manufacturer": "Greycat Industrial",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Medium backpack. 127.5K uSCU carrying capacity. Pairs with Strata armor.",
     "price_auec": 4800,
     "locations": ["Armor shops (most stations)", "Greycat showrooms"],
     "loot_locations": ["Distribution Centers", "Faction facility loot"],
     "variants": ["Strata Backpack ArcCorp Black", "Strata Backpack ArcCorp Edition", "Strata Backpack Crusader Black", "Strata Backpack Crusader Edition", "Strata Backpack Greycat Edition", "Strata Backpack Heatwave", "Strata Backpack Hurston Black", "Strata Backpack Hurston Edition", "Strata Backpack microTech Black", "Strata Backpack microTech Edition", "Strata Backpack Pyrotechnic Edition", "Strata Backpack Shubin Edition"]},

    {"id": "testudo-backpack", "name": "Testudo Backpack", "type": "Backpack", "manufacturer": "Quirinus Tech",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Medium backpack. 105K uSCU carrying capacity. Pairs with Testudo armor.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Ground defense operations", "Bunker loot crates"],
     "variants": ["Testudo Backpack Clanguard", "Testudo Backpack Combustion", "Testudo Backpack Deathblow", "Testudo Backpack Disrupt Camo", "Testudo Backpack Earthshake", "Testudo Backpack Nightveil", "Testudo Backpack Turfwar"]},

    {"id": "warden-backpack", "name": "Warden Backpack", "type": "Backpack", "manufacturer": "Virgil",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy backpack. 150K uSCU carrying capacity. Loot only.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Security facility loot", "High-threat NPC drops"],
     "variants": ["Warden Backpack Epoque"]},

    {"id": "zeus-exploration-backpack", "name": "Zeus Exploration Backpack", "type": "Backpack", "manufacturer": "Roberts Space Industries",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy exploration backpack. 180K uSCU capacity.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Rare exploration site loot", "Frontier outpost crates"],
     "variants": ["Zeus Exploration Backpack Starscape"]},

    {"id": "zeus-exploration-suit-backpack", "name": "Zeus Exploration Suit Backpack", "type": "Backpack", "manufacturer": "Roberts Space Industries",
     "temp_max": 0, "temp_min": 0, "radiation": 0,
     "description": "Heavy exploration backpack. 180K uSCU. Pairs with Zeus Exploration Suit.",
     "price_auec": 0,
     "locations": [],
     "loot_locations": ["Rare exploration loot", "Event exclusive drops"],
     "variants": ["Zeus Exploration Suit Backpack Solar"]},
]


def get_all_fps_weapons():
    return FPS_WEAPONS

def get_all_armor_sets():
    return ARMOR_SETS

def get_all_equipment():
    return EQUIPMENT


# === EQUIPMENT: Mining, Medical, Backpacks, Undersuits ===
EQUIPMENT = [
    # === MINING HEADS ===
    {"id": "arbor-mh1", "name": "Arbor MH1 Mining Head", "type": "Mining Head", "subtype": "Ship", "manufacturer": "Greycat Industrial",
     "stats": {"power": 3, "range": "200m", "resistance": "Low", "optimal_charge": "30-50%"},
     "description": "Starter mining head for Prospector. Low power, good for softer rocks.",
     "locations": ["Cargo Decks (most stations)", "Shubin Mining (all locations)"],
     "price_auec": 13000, "variants": []},

    {"id": "helix-mh1", "name": "Helix I Mining Head", "type": "Mining Head", "subtype": "Ship", "manufacturer": "Argo Astronautics",
     "stats": {"power": 5, "range": "200m", "resistance": "Medium", "optimal_charge": "25-55%"},
     "description": "Mid-tier mining head. Wider optimal charge window, more forgiving.",
     "locations": ["Shubin Mining (Lorville)", "Cargo Decks (Area 18)"],
     "price_auec": 82400, "variants": []},

    {"id": "lancet-mh1", "name": "Lancet MH1 Mining Head", "type": "Mining Head", "subtype": "Ship", "manufacturer": "Thermyte Concern",
     "stats": {"power": 4, "range": "250m", "resistance": "Medium", "optimal_charge": "20-60%"},
     "description": "Precision mining head. Best optimal window, ideal for quantanium.",
     "locations": ["Shubin Mining (New Babbage)", "ARC Mining (Orison)"],
     "price_auec": 108000, "variants": []},

    {"id": "hofstede-s1", "name": "Hofstede S1 Mining Head", "type": "Mining Head", "subtype": "Ship", "manufacturer": "Greycat Industrial",
     "stats": {"power": 6, "range": "200m", "resistance": "High", "optimal_charge": "35-50%"},
     "description": "High-power mining head. Cracks tougher deposits but narrower charge window.",
     "locations": ["Shubin Mining (Hurston)", "Cargo Decks (Lorville)"],
     "price_auec": 122000, "variants": []},

    {"id": "klein-s1", "name": "Klein S1 Mining Head", "type": "Mining Head", "subtype": "Ship", "manufacturer": "Thermyte Concern",
     "stats": {"power": 7, "range": "200m", "resistance": "Very High", "optimal_charge": "40-55%"},
     "description": "Top-tier mining head. Highest power, needed for the hardest rocks.",
     "locations": ["Shubin Mining (Area 18)", "Tammany & Sons (Levski)"],
     "price_auec": 146000, "variants": []},

    # === HAND MINING TOOLS ===
    {"id": "multitool-ore", "name": "OreBit Mining Attachment", "type": "Mining Attachment", "subtype": "Hand", "manufacturer": "Greycat Industrial",
     "stats": {"power": 1, "range": "15m", "resistance": "Low", "optimal_charge": "30-60%"},
     "description": "Multi-tool mining attachment. Mine hand-mineable deposits for gems and hadanite.",
     "locations": ["Cargo Decks (all stations)", "Mining outposts"],
     "price_auec": 1750, "variants": []},

    # === MINING CONSUMABLES ===
    {"id": "surge-module", "name": "Surge Mining Module", "type": "Mining Module", "subtype": "Consumable", "manufacturer": "Shubin Interstellar",
     "stats": {"effect": "+30% laser power for 4s", "charges": 4},
     "description": "Temporarily boosts mining laser power. Essential for cracking quantanium.",
     "locations": ["Shubin Mining (all locations)", "Cargo Decks"],
     "price_auec": 2200, "variants": []},

    {"id": "stampede-module", "name": "Stampede Mining Module", "type": "Mining Module", "subtype": "Consumable", "manufacturer": "Shubin Interstellar",
     "stats": {"effect": "+20% resistance reduction for 5s", "charges": 4},
     "description": "Reduces rock resistance temporarily. Pairs well with lower-power heads.",
     "locations": ["Shubin Mining (all locations)", "Cargo Decks"],
     "price_auec": 2800, "variants": []},

    {"id": "brandt-module", "name": "Brandt Mining Module", "type": "Mining Module", "subtype": "Consumable", "manufacturer": "Shubin Interstellar",
     "stats": {"effect": "+15% optimal window width for 6s", "charges": 4},
     "description": "Widens optimal charge window. Safer mining, less risk of overcharge.",
     "locations": ["Shubin Mining (most locations)", "Cargo Decks"],
     "price_auec": 1800, "variants": []},

    {"id": "forel-module", "name": "Forel Mining Module", "type": "Mining Module", "subtype": "Consumable", "manufacturer": "Shubin Interstellar",
     "stats": {"effect": "Reduces instability by 40%", "charges": 3},
     "description": "Stabilizes volatile rocks. Critical for quantanium to prevent detonation.",
     "locations": ["Shubin Mining (New Babbage)", "Cargo Decks (Port Tressler)"],
     "price_auec": 3200, "variants": []},

    # === MEDICAL SUPPLIES ===
    {"id": "medgun-paramedic", "name": "CuraLife Medical Gun (Paramedic)", "type": "Medical Device", "subtype": "Tool", "manufacturer": "CureLife",
     "stats": {"heal_rate": "Fast", "range": "5m", "drug_capacity": 4},
     "description": "Long-range medical device. Heal teammates from a distance. Essential for group play.",
     "locations": ["Pharmacies (all landing zones)", "Medical supply vendors"],
     "price_auec": 5500, "variants": []},

    {"id": "medpen-mk2", "name": "MedPen Mk II", "type": "Medical Device", "subtype": "Consumable", "manufacturer": "CureLife",
     "stats": {"heal_amount": "Major wounds", "blood_drug_level": "+15%"},
     "description": "Enhanced medical injector. Heals major wounds but adds drug toxicity.",
     "locations": ["Pharmacies (all landing zones)", "Medical kiosks"],
     "price_auec": 350, "variants": []},

    {"id": "hemozal", "name": "Hemozal", "type": "Medical Device", "subtype": "Consumable", "manufacturer": "CureLife",
     "stats": {"effect": "Removes blood drug level", "charges": 1},
     "description": "Detox injector. Clears accumulated drug effects from medical treatments.",
     "locations": ["Pharmacies (Orison, New Babbage)", "Hospital kiosks"],
     "price_auec": 200, "variants": []},

    {"id": "medical-stretcher", "name": "Medical Stretcher", "type": "Medical Device", "subtype": "Equipment", "manufacturer": "CureLife",
     "stats": {"capacity": "1 patient", "effect": "Stabilize + transport"},
     "description": "Deployable stretcher for transporting downed players. Used in Apollo/Cutlass Red.",
     "locations": ["Medical supply vendors", "Ship medical bays"],
     "price_auec": 0, "variants": []},

    # === BACKPACKS ===
    # === UNDERSUITS ===
    {"id": "alantin-undersuit", "name": "Alantin Undersuit", "type": "Undersuit", "subtype": "Standard", "manufacturer": "RSI",
     "stats": {"temp_max": 50, "temp_min": -20, "o2_capacity": "10 min"},
     "description": "Basic undersuit. Worn under all armor sets. Standard life support.",
     "locations": ["Clothing shops (all stations)", "Default starter gear"],
     "price_auec": 800, "variants": ["Alantin White", "Alantin Black"]},

    {"id": "venture-undersuit", "name": "Venture Undersuit", "type": "Undersuit", "subtype": "Exploration", "manufacturer": "RSI",
     "stats": {"temp_max": 65, "temp_min": -35, "o2_capacity": "15 min"},
     "description": "Enhanced exploration undersuit. Better temperature range and O2 capacity.",
     "locations": ["Clothing shops (New Babbage, Orison)", "Dumper's Depot"],
     "price_auec": 2200, "variants": ["Venture Pathfinder"]},

    {"id": "arden-undersuit", "name": "Arden Undersuit", "type": "Undersuit", "subtype": "Tactical", "manufacturer": "Roussimoff",
     "stats": {"temp_max": 55, "temp_min": -25, "o2_capacity": "12 min"},
     "description": "Tactical undersuit with reinforced weave. Slightly better damage mitigation.",
     "locations": ["Armor shops (Lorville)", "Military surplus"],
     "price_auec": 1500, "variants": ["Arden Black", "Arden Navy"]},

    {"id": "novikov-undersuit", "name": "Novikov Undersuit", "type": "Undersuit", "subtype": "Cold Weather", "manufacturer": "Odin Munitions",
     "stats": {"temp_max": 45, "temp_min": -55, "o2_capacity": "14 min"},
     "description": "Cold-weather specialist undersuit. Best-in-class cold protection.",
     "locations": ["Hatter Station (microTech)", "New Babbage shops"],
     "price_auec": 3000, "variants": []},

    {"id": "pembroke-undersuit", "name": "Pembroke Undersuit", "type": "Undersuit", "subtype": "Heat Resistant", "manufacturer": "RSI",
     "stats": {"temp_max": 85, "temp_min": -10, "o2_capacity": "14 min"},
     "description": "Heat-resistant undersuit. Essential for extreme heat environments.",
     "locations": ["Cargo Decks (Lorville)", "Armor shops (ArcCorp)"],
     "price_auec": 3400, "variants": []},

    # === SALVAGE TOOLS ===
    {"id": "salvage-multitool", "name": "Salvage Attachment (Multi-Tool)", "type": "Salvage Tool", "subtype": "Hand", "manufacturer": "Greycat Industrial",
     "stats": {"range": "8m", "rate": "Slow", "material": "RMC"},
     "description": "Multi-tool salvage attachment. Strip hull materials (RMC) from derelict ships by hand.",
     "locations": ["Cargo Decks (all stations)", "Dumper's Depot"],
     "price_auec": 2100, "variants": []},

    {"id": "reclaimer-claw", "name": "Reclaimer Salvage Claw", "type": "Salvage Tool", "subtype": "Ship", "manufacturer": "Aegis Dynamics",
     "stats": {"range": "50m", "rate": "Fast", "material": "RMC + Components"},
     "description": "Ship-mounted industrial salvage arm. Strips ships at scale. Exclusive to Reclaimer.",
     "locations": ["Included with Reclaimer", "Cannot be purchased separately"],
     "price_auec": 0, "variants": []},

    {"id": "vulture-scraper", "name": "Vulture Scraper Module", "type": "Salvage Tool", "subtype": "Ship", "manufacturer": "Drake Interplanetary",
     "stats": {"range": "30m", "rate": "Medium", "material": "RMC"},
     "description": "Medium salvage beam for the Vulture. Good balance of speed and capacity.",
     "locations": ["Included with Vulture", "Cannot be purchased separately"],
     "price_auec": 0, "variants": []},

    # === SCANNING TOOLS ===
    {"id": "scanning-module", "name": "Scanning Attachment (Multi-Tool)", "type": "Scanner", "subtype": "Hand", "manufacturer": "Greycat Industrial",
     "stats": {"range": "100m", "detection": "Mineral deposits, items, NPCs"},
     "description": "Multi-tool scanning attachment. Detect mineable deposits and lootable items.",
     "locations": ["Cargo Decks (all stations)", "Mining outposts"],
     "price_auec": 1500, "variants": []},

    {"id": "ping-scanner", "name": "Ship Ping Scanner", "type": "Scanner", "subtype": "Ship", "manufacturer": "Various",
     "stats": {"range": "Varies by radar", "detection": "Ships, stations, POIs"},
     "description": "Built-in ship scanner. Range depends on installed radar component.",
     "locations": ["Default on all ships", "Upgrade via radar components"],
     "price_auec": 0, "variants": []},

    # === HACKING TOOLS ===
    {"id": "crypto-key", "name": "CryptoKey", "type": "Hacking Tool", "subtype": "Consumable", "manufacturer": "Coda Systems",
     "stats": {"uses": 1, "effect": "Bypass security panel", "success_rate": "75%"},
     "description": "Single-use hacking chip. Bypass locked doors and security panels in bunkers.",
     "locations": ["Grim HEX", "Looted from outlaw NPCs", "Rare loot from bunkers"],
     "price_auec": 500, "variants": []},

    {"id": "e-warfare-device", "name": "E-War Device", "type": "Hacking Tool", "subtype": "Ship", "manufacturer": "Aegis Dynamics",
     "stats": {"range": "3km", "effect": "Disrupt target systems", "duration": "8s"},
     "description": "Ship-mounted electronic warfare suite. Disrupts enemy shields and targeting. Vanguard Sentinel exclusive.",
     "locations": ["Included with Vanguard Sentinel"],
     "price_auec": 0, "variants": []},
]
