"""Ship in-game purchase locations and prices from starcitizen.tools wiki (Alpha 4.6.0)"""

# Dealers
ASTRO_ARMADA = "Astro Armada (Area18)"
CRUSADER_SHOWROOM = "Crusader Showroom (Orison)"
NEW_DEAL = "New Deal (Lorville)"
TEACHS = "Teach's Ship Shop (Levski)"
BUY_FLY = "Buy & Fly (Ruin Station)"

# ship_name -> { base_price_auec, dealers: [{name, has_stock}] }
# Source: https://starcitizen.tools/Purchasing_ships (Updated: Jan 31, 2026 - Alpha 4.6.0)
SHIP_PURCHASE_DATA = {
    "Avenger Stalker": {"price_auec": 1587600, "dealers": [NEW_DEAL]},
    "Avenger Titan": {"price_auec": 1358280, "dealers": [NEW_DEAL, TEACHS]},
    "Avenger Titan Renegade": {"price_auec": 1852200, "dealers": [NEW_DEAL]},
    "Avenger Warlock": {"price_auec": 2249100, "dealers": [NEW_DEAL]},
    "Eclipse": {"price_auec": 7938000, "dealers": [NEW_DEAL]},
    "Gladius": {"price_auec": 2381400, "dealers": [NEW_DEAL, TEACHS]},
    "Gladius Valiant": {"price_auec": 2910600, "dealers": [NEW_DEAL]},
    "Hammerhead": {"price_auec": 47958752, "dealers": [NEW_DEAL]},
    "Reclaimer": {"price_auec": 31752000, "dealers": [NEW_DEAL, TEACHS]},
    "Redeemer": {"price_auec": 17199000, "dealers": [NEW_DEAL]},
    "Retaliator": {"price_auec": 7938000, "dealers": [NEW_DEAL]},
    "Sabre": {"price_auec": 4498200, "dealers": [NEW_DEAL]},
    "Sabre Comet": {"price_auec": 4650345, "dealers": [NEW_DEAL]},
    "Sabre Firebird": {"price_auec": 5580414, "dealers": [NEW_DEAL]},
    "Sabre Peregrine": {"price_auec": 3845961, "dealers": [NEW_DEAL]},
    "Vanguard Harbinger": {"price_auec": 11510100, "dealers": [NEW_DEAL]},
    "Vanguard Hoplite": {"price_auec": 9327150, "dealers": [NEW_DEAL]},
    "Vanguard Sentinel": {"price_auec": 10914750, "dealers": [NEW_DEAL]},
    "Vanguard Warden": {"price_auec": 10319400, "dealers": [NEW_DEAL]},
    "Arrow": {"price_auec": 1984500, "dealers": [ASTRO_ARMADA, TEACHS]},
    "Asgard": {"price_auec": 17860500, "dealers": [ASTRO_ARMADA]},
    "Ballista": {"price_auec": 1481760, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Centurion": {"price_auec": 1164240, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "C8 Pisces": {"price_auec": 745290, "dealers": [ASTRO_ARMADA]},
    "C8R Pisces Rescue": {"price_auec": 555660, "dealers": [ASTRO_ARMADA]},
    "C8X Pisces Expedition": {"price_auec": 515970, "dealers": [ASTRO_ARMADA]},
    "Carrack": {"price_auec": 34398000, "dealers": [ASTRO_ARMADA]},
    "F7C Hornet Mk II": {"price_auec": 4895100, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "F7C-S Hornet Ghost Mk II": {"price_auec": 5384600, "dealers": [NEW_DEAL]},
    "F7C-R Hornet Tracker Mk II": {"price_auec": 5139850, "dealers": [NEW_DEAL]},
    "F7C Hornet Mk I": {"price_auec": 2910600, "dealers": [ASTRO_ARMADA]},
    "F7C Hornet Wildfire Mk I": {"price_auec": 4630500, "dealers": [ASTRO_ARMADA]},
    "F7C-M Super Hornet Mk I": {"price_auec": 4762800, "dealers": [ASTRO_ARMADA]},
    "F7C-S Hornet Ghost Mk I": {"price_auec": 3307500, "dealers": [ASTRO_ARMADA]},
    "F7C-R Hornet Tracker Mk I": {"price_auec": 3210480, "dealers": [ASTRO_ARMADA]},
    "Gladiator": {"price_auec": 4365900, "dealers": [ASTRO_ARMADA]},
    "Hawk": {"price_auec": 2646000, "dealers": [ASTRO_ARMADA]},
    "Hurricane": {"price_auec": 5556600, "dealers": [ASTRO_ARMADA]},
    "Spartan": {"price_auec": 846720, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Terrapin": {"price_auec": 5433120, "dealers": [ASTRO_ARMADA, TEACHS]},
    "Terrapin Medic": {"price_auec": 5704770, "dealers": [ASTRO_ARMADA]},
    "Valkyrie": {"price_auec": 19845000, "dealers": [ASTRO_ARMADA]},
    "Khartu-al": {"price_auec": 7229250, "dealers": [ASTRO_ARMADA]},
    "Nox": {"price_auec": 722925, "dealers": [ASTRO_ARMADA]},
    "San'tok.yāi": {"price_auec": 9355500, "dealers": [ASTRO_ARMADA]},
    "ATLS": {"price_auec": 75600, "dealers": [ASTRO_ARMADA, CRUSADER_SHOWROOM, NEW_DEAL, TEACHS, BUY_FLY]},
    "ATLS GEO": {"price_auec": 90720, "dealers": [ASTRO_ARMADA, CRUSADER_SHOWROOM, NEW_DEAL, TEACHS]},
    "CSV-SM": {"price_auec": 378000, "dealers": [CRUSADER_SHOWROOM, NEW_DEAL]},
    "MOLE": {"price_auec": 8930250, "dealers": [NEW_DEAL, TEACHS]},
    "MPUV Cargo": {"price_auec": 330750, "dealers": [NEW_DEAL]},
    "MPUV Personnel": {"price_auec": 378000, "dealers": [NEW_DEAL]},
    "MPUV Tractor": {"price_auec": 415800, "dealers": [NEW_DEAL, TEACHS]},
    "RAFT": {"price_auec": 3543750, "dealers": [NEW_DEAL, TEACHS]},
    "SRV": {"price_auec": 3969000, "dealers": [NEW_DEAL, TEACHS]},
    "Defender": {"price_auec": 6237000, "dealers": [ASTRO_ARMADA]},
    "HoverQuad": {"price_auec": 56700, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Mustang Alpha": {"price_auec": 642600, "dealers": [NEW_DEAL, TEACHS]},
    "Mustang Beta": {"price_auec": 655200, "dealers": [NEW_DEAL]},
    "Mustang Delta": {"price_auec": 1228500, "dealers": [ASTRO_ARMADA]},
    "Mustang Gamma": {"price_auec": 1178100, "dealers": [ASTRO_ARMADA]},
    "Nomad": {"price_auec": 1512000, "dealers": [NEW_DEAL, TEACHS]},
    "Ares Inferno": {"price_auec": 4725000, "dealers": [CRUSADER_SHOWROOM]},
    "Ares Star Fighter Inferno": {"price_auec": 4725000, "dealers": [CRUSADER_SHOWROOM]},
    "Ares Ion": {"price_auec": 4725000, "dealers": [CRUSADER_SHOWROOM]},
    "Ares Star Fighter Ion": {"price_auec": 4725000, "dealers": [CRUSADER_SHOWROOM]},
    "A1 Spirit": {"price_auec": 4961250, "dealers": [CRUSADER_SHOWROOM]},
    "A2 Hercules Starlifter": {"price_auec": 44296876, "dealers": [CRUSADER_SHOWROOM, TEACHS]},
    "C1 Spirit": {"price_auec": 3118500, "dealers": [CRUSADER_SHOWROOM]},
    "C2 Hercules Starlifter": {"price_auec": 18900000, "dealers": [ASTRO_ARMADA, CRUSADER_SHOWROOM]},
    "Intrepid": {"price_auec": 705600, "dealers": [ASTRO_ARMADA, CRUSADER_SHOWROOM, NEW_DEAL]},
    "M2 Hercules Starlifter": {"price_auec": 29484000, "dealers": [CRUSADER_SHOWROOM, NEW_DEAL]},
    "Mercury Star Runner": {"price_auec": 12285000, "dealers": [CRUSADER_SHOWROOM]},
    "Buccaneer": {"price_auec": 1663200, "dealers": [NEW_DEAL, BUY_FLY]},
    "Caterpillar": {"price_auec": 12474000, "dealers": [NEW_DEAL]},
    "Corsair": {"price_auec": 6552000, "dealers": [NEW_DEAL]},
    "Cutlass Black": {"price_auec": 2116800, "dealers": [NEW_DEAL]},
    "Cutlass Blue": {"price_auec": 3704400, "dealers": [NEW_DEAL]},
    "Cutlass Red": {"price_auec": 2857680, "dealers": [NEW_DEAL, BUY_FLY]},
    "Cutlass Steel": {"price_auec": 3997350, "dealers": [NEW_DEAL]},
    "Cutter": {"price_auec": 635040, "dealers": [NEW_DEAL, TEACHS]},
    "Cutter Rambler": {"price_auec": 740880, "dealers": [NEW_DEAL]},
    "Cutter Scout": {"price_auec": 705600, "dealers": [NEW_DEAL]},
    "Dragonfly": {"price_auec": 342720, "dealers": [NEW_DEAL, BUY_FLY]},
    "Dragonfly Yellowjacket": {"price_auec": 342720, "dealers": [NEW_DEAL]},
    "Golem": {"price_auec": 1058400, "dealers": [NEW_DEAL, TEACHS]},
    "Herald": {"price_auec": 1285200, "dealers": [NEW_DEAL]},
    "Mule": {"price_auec": 68040, "dealers": [NEW_DEAL, TEACHS]},
    "Vulture": {"price_auec": 2646000, "dealers": [NEW_DEAL, TEACHS, BUY_FLY]},
    "Blade": {"price_auec": 7796250, "dealers": [ASTRO_ARMADA]},
    "Prowler": {"price_auec": 18711000, "dealers": [ASTRO_ARMADA]},
    "Prowler Utility": {"price_auec": 18711000, "dealers": [ASTRO_ARMADA]},
    "Talon": {"price_auec": 3260250, "dealers": [ASTRO_ARMADA]},
    "Talon Shrike": {"price_auec": 3260250, "dealers": [ASTRO_ARMADA]},
    "Syulen": {"price_auec": 2778300, "dealers": [ASTRO_ARMADA]},
    "MTC": {"price_auec": 79580, "dealers": [NEW_DEAL]},
    "PTV": {"price_auec": 28350, "dealers": [ASTRO_ARMADA, TEACHS]},
    "ROC": {"price_auec": 103950, "dealers": [NEW_DEAL, TEACHS]},
    "ROC-DS": {"price_auec": 141750, "dealers": [NEW_DEAL, TEACHS]},
    "STV": {"price_auec": 75600, "dealers": [ASTRO_ARMADA, BUY_FLY]},
    "P-52 Merlin": {"price_auec": 283500, "dealers": [ASTRO_ARMADA]},
    "P-72 Archimedes": {"price_auec": 449820, "dealers": [ASTRO_ARMADA]},
    "Fury": {"price_auec": 727650, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Fury LX": {"price_auec": 824670, "dealers": [ASTRO_ARMADA]},
    "Fury MX": {"price_auec": 727650, "dealers": [NEW_DEAL]},
    "Guardian": {"price_auec": 6615000, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Guardian MX": {"price_auec": 7408800, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Pulse": {"price_auec": 185220, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Pulse LX": {"price_auec": 211680, "dealers": [NEW_DEAL]},
    "Razor": {"price_auec": 1863540, "dealers": [NEW_DEAL]},
    "Razor EX": {"price_auec": 1757700, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Razor LX": {"price_auec": 1927800, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Fortune": {"price_auec": 1890000, "dealers": [NEW_DEAL, TEACHS]},
    "Freelancer": {"price_auec": 2962575, "dealers": [NEW_DEAL]},
    "Freelancer DUR": {"price_auec": 3151103, "dealers": [NEW_DEAL, TEACHS]},
    "Freelancer MAX": {"price_auec": 4039875, "dealers": [NEW_DEAL]},
    "Freelancer MIS": {"price_auec": 4713188, "dealers": [NEW_DEAL]},
    "Hull A": {"price_auec": 1615950, "dealers": [NEW_DEAL, TEACHS]},
    "Hull C": {"price_auec": 15710625, "dealers": [NEW_DEAL]},
    "Prospector": {"price_auec": 2929500, "dealers": [NEW_DEAL, BUY_FLY]},
    "Reliant Kore": {"price_auec": 1719900, "dealers": [NEW_DEAL, TEACHS]},
    "Reliant Mako": {"price_auec": 2513700, "dealers": [NEW_DEAL]},
    "Reliant Sen": {"price_auec": 2249100, "dealers": [NEW_DEAL]},
    "Reliant Tana": {"price_auec": 1984500, "dealers": [NEW_DEAL]},
    "Starfarer": {"price_auec": 12568500, "dealers": [NEW_DEAL, TEACHS]},
    "Starfarer Gemini": {"price_auec": 14244300, "dealers": [NEW_DEAL]},
    "Starlancer MAX": {"price_auec": 8820000, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Starlancer TAC": {"price_auec": 13381200, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "85X": {"price_auec": 573300, "dealers": [NEW_DEAL]},
    "100i": {"price_auec": 1146600, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "125a": {"price_auec": 1587600, "dealers": [NEW_DEAL]},
    "135c": {"price_auec": 1490580, "dealers": [ASTRO_ARMADA]},
    "300i": {"price_auec": 1375920, "dealers": [ASTRO_ARMADA]},
    "315p": {"price_auec": 1490580, "dealers": [ASTRO_ARMADA]},
    "325a": {"price_auec": 1852200, "dealers": [ASTRO_ARMADA]},
    "350r": {"price_auec": 3748500, "dealers": [ASTRO_ARMADA]},
    "400i": {"price_auec": 11466000, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "600i": {"price_auec": 27231750, "dealers": [ASTRO_ARMADA]},
    "600i Explorer": {"price_auec": 27231750, "dealers": [ASTRO_ARMADA]},
    "600i Touring": {"price_auec": 24938550, "dealers": [ASTRO_ARMADA]},
    "890 Jump": {"price_auec": 65356200, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "M50": {"price_auec": 1499400, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "X1": {"price_auec": 105840, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "X1 Force": {"price_auec": 132300, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "X1 Velocity": {"price_auec": 119070, "dealers": [ASTRO_ARMADA, NEW_DEAL]},
    "Apollo Medivac": {"price_auec": 8295210, "dealers": [TEACHS]},
    "Apollo Triage": {"price_auec": 7541100, "dealers": [TEACHS]},
    "Aurora CL": {"price_auec": 1020600, "dealers": [NEW_DEAL, TEACHS]},
    "Aurora ES": {"price_auec": 423360, "dealers": [NEW_DEAL, TEACHS]},
    "Aurora LN": {"price_auec": 907200, "dealers": [NEW_DEAL]},
    "Aurora LX": {"price_auec": 687960, "dealers": [NEW_DEAL]},
    "Aurora MR": {"price_auec": 680400, "dealers": [NEW_DEAL]},
    "Constellation Andromeda": {"price_auec": 10160640, "dealers": [NEW_DEAL]},
    "Constellation Aquila": {"price_auec": 12186720, "dealers": [NEW_DEAL]},
    "Constellation Phoenix": {"price_auec": 14817600, "dealers": [NEW_DEAL]},
    "Constellation Taurus": {"price_auec": 8043840, "dealers": [NEW_DEAL, TEACHS]},
    "Lynx": {"price_auec": 136080, "dealers": [NEW_DEAL]},
    "Mantis": {"price_auec": 3402000, "dealers": [NEW_DEAL]},
    "Meteor": {"price_auec": 4536000, "dealers": [NEW_DEAL]},
    "Scorpius": {"price_auec": 5443200, "dealers": [NEW_DEAL]},
    "Scorpius Antares": {"price_auec": 5525517, "dealers": [NEW_DEAL]},
    "Ursa": {"price_auec": 120186, "dealers": [NEW_DEAL]},
    "Ursa Rover": {"price_auec": 120186, "dealers": [NEW_DEAL]},
    "Ursa Medivac": {"price_auec": 137200, "dealers": [NEW_DEAL, TEACHS]},
    "Zeus Mk II ES": {"price_auec": 4422600, "dealers": [NEW_DEAL]},
    "Zeus Mk II CL": {"price_auec": 6804000, "dealers": [NEW_DEAL]},
    "Cyclone": {"price_auec": 110170, "dealers": [NEW_DEAL, BUY_FLY]},
    "Cyclone AA": {"price_auec": 160247, "dealers": [NEW_DEAL]},
    "Cyclone MT": {"price_auec": 150232, "dealers": [NEW_DEAL]},
    "Cyclone RC": {"price_auec": 130201, "dealers": [NEW_DEAL]},
    "Cyclone RN": {"price_auec": 130201, "dealers": [NEW_DEAL]},
    "Cyclone TR": {"price_auec": 130201, "dealers": [NEW_DEAL]},
    "Nova": {"price_auec": 961482, "dealers": [NEW_DEAL, BUY_FLY]},
    "Storm": {"price_auec": 453600, "dealers": [NEW_DEAL]},
    "Storm AA": {"price_auec": 476280, "dealers": [NEW_DEAL]},
}


def get_purchase_info(ship_name: str) -> dict:
    """Get in-game purchase info for a ship by name."""
    data = SHIP_PURCHASE_DATA.get(ship_name)
    if data:
        return {
            "price_auec": data["price_auec"],
            "dealers": data["dealers"],
        }
    return {"price_auec": 0, "dealers": []}
