"""Static Wikelo contract data from starcitizen.tools/Wikelo"""

WIKELO_INFO = {
    "name": "Wikelo",
    "race": "Banu",
    "occupation": "Trader",
    "system": "Stanton",
    "description": "Wikelo is a Banu trader and mission giver based in Stanton. He recently retired from a fabrication Souli in the Banu Protectorate and set up shop in human space.",
    "image": "https://media.starcitizen.tools/thumb/8/83/Wikelo_Hologram_-_Alpha_4.1.0.jpg/400px-Wikelo_Hologram_-_Alpha_4.1.0.jpg.webp",
    "locations": [
        {"name": "Wikelo Emporium Dasi Station", "near": "Hurston"},
        {"name": "Wikelo Emporium Selo Station", "near": "Yela"},
        {"name": "Wikelo Emporium Kinga Station", "near": "microTech"},
    ],
    "reputation_ranks": ["New Customer", "Very Good Customer", "Very Best Customer"],
    "intro_mission": {
        "name": "New to System",
        "items_needed": ["1x Vestal Water", "3x Tundra Kopion Horn"],
    },
}

WIKELO_CONTRACTS = [
    # === CURRENCIES ===
    {"id": "trade-merc-scrip", "name": "Trade Merc Scrip for Favors?", "category": "Currencies", "active": True,
     "items_needed": ["50x MG Scrip"], "reward": ["1x Wikelo Favor"],
     "image": None},
    {"id": "trade-council-scrip", "name": "Trade Council Scrip for Favors?", "category": "Currencies", "active": True,
     "items_needed": ["50x Council Scrip"], "reward": ["1x Wikelo Favor"],
     "image": None},
    {"id": "turn-things-to-favor", "name": "Turn Things to Favor", "category": "Currencies", "active": True,
     "items_needed": ["50x Carinite"], "reward": ["1x Wikelo Favor"],
     "image": None},
    {"id": "trade-worm-parts", "name": "Trade Worm Parts for Favors?", "category": "Currencies", "active": True,
     "items_needed": ["12x Irradiated Valakkar Pearl (Grade AA)"], "reward": ["1x Wikelo Favor"],
     "image": None},
    {"id": "want-polaris-bit", "name": "Want Polaris? Need something special.", "category": "Currencies", "active": True,
     "items_needed": ["24 SCU of Quantanium"], "reward": ["1x Polaris Bit"],
     "image": None},

    # === WEAPONS ===
    {"id": "curious-weapon", "name": "Curious Weapon", "category": "Weapons", "active": True,
     "items_needed": ["1x Boomtube Rocket Launcher", "2x Vanduul Plating", "2x Vanduul Metal"],
     "reward": ['1x Boomtube "Clanguard" Rocket Launcher'],
     "image": "https://media.starcitizen.tools/d/da/Curious_Weapon.png"},
    {"id": "fun-kopion-skull-gun", "name": "Fun Kopion Skull Gun", "category": "Weapons", "active": True,
     "items_needed": ["10x Carinite", "15x Saldynium (Ore)", "1x Parallax Energy Assault Rifle", "20x Tundra Kopion Horn", "20x Jaclium (Ore)"],
     "reward": ['1x Parallax "Fun Kopion Skull" Energy Assault Rifle'],
     "image": "https://media.starcitizen.tools/7/77/Kopion_Skull_Right.png"},
    {"id": "fun-military-skull-gun", "name": "Fun Military Skull Gun", "category": "Weapons", "active": True,
     "items_needed": ["10x Carinite", "15x Saldynium (Ore)", "1x Parallax Energy Assault Rifle", "20x Irradiated Valakkar Fang (Juvenile)", "20x Jaclium (Ore)"],
     "reward": ['1x Parallax "Fun Military Skull" Energy Assault Rifle'],
     "image": "https://media.starcitizen.tools/d/de/Fun_Military_Skull_Gun.png"},
    {"id": "fun-kopion-tooth-gun", "name": "Fun Kopion Tooth Gun", "category": "Weapons", "active": False,
     "items_needed": ["40x Jaclium (Ore)", "30x Saldynium (Ore)", "20x Carinite", "1x Parallax Energy Assault Rifle", "35x Tundra Kopion Horn"],
     "reward": ['1x Parallax "Fun Kopion Tooth" Energy Assault Rifle'],
     "image": "https://media.starcitizen.tools/d/dc/Kopion_Tooth_Right.png"},
    {"id": "fun-military-tooth-gun", "name": "Fun Military Tooth Gun", "category": "Weapons", "active": False,
     "items_needed": ["40x Jaclium (Ore)", "30x Saldynium (Ore)", "20x Carinite", "1x Parallax Energy Assault Rifle", "35x Irradiated Valakkar Fang (Juvenile)"],
     "reward": ['1x Parallax "Fun Military Tooth" Energy Assault Rifle'],
     "image": "https://media.starcitizen.tools/f/f1/Fun_Military_Tooth_Right.png"},
    {"id": "make-volt-shotgun-angrier", "name": "Make VOLT shotgun angrier", "category": "Weapons", "active": True,
     "items_needed": ["1x Prism Laser Shotgun", "5x Irradiated Valakkar Fang (Juvenile)", "10x Irradiated Valakkar Fang (Adult)"],
     "reward": ['1x Prism "Irradiated" Laser Shotgun'],
     "image": "https://media.starcitizen.tools/b/b0/Make_VOLT_shotgun_angrier.png"},
    {"id": "snow-snipe", "name": "Snow Snipe", "category": "Weapons", "active": True,
     "items_needed": ["7x ASD Secure Drive", "1x Zenith Laser Sniper Rifle"],
     "reward": ['1x Zenith "Snow Camo" Laser Sniper Rifle'],
     "image": None},
    {"id": "heavy-volt-zapper", "name": "Heavy Volt Zapper", "category": "Weapons", "active": False,
     "items_needed": ["1x Fresnel Energy LMG", "5x ASD Secure Drive", "5x RCMBNT-XTL-1", "5x RCMBNT-XTL-2", "5x RCMBNT-XTL-3"],
     "reward": ['1x Fresnel "Deepwater" Energy LMG'],
     "image": "https://media.starcitizen.tools/1/16/Heavy_Volt_Zapper.png"},
    {"id": "yormandi-gun", "name": "Yormandi Gun", "category": "Weapons", "active": True,
     "items_needed": ["6x Yormandi Eye", "3x Yormandi Tongue", "1x Fresnel Energy LMG"],
     "reward": ['1x Fresnel "Yormandi" LMG'],
     "image": "https://media.starcitizen.tools/8/8d/Yormandi_Gun.png"},
    {"id": "volt-gun-navy", "name": "Volt gun more Navy-like", "category": "Weapons", "active": False,
     "items_needed": ["1x Quartz Energy SMG", "30x MG Scrip", "5x Ace Interceptor Helmet", "50x Grassland Quasi Grazer Egg"],
     "reward": ['1x Quartz "Cobalt Camo" Energy SMG'],
     "image": "https://media.starcitizen.tools/b/be/Quartz_%22Cobalt_Camo%22_Energy_SMG.png"},
    {"id": "zappy-gun-woodlike", "name": "Zappy gun more woodlike", "category": "Weapons", "active": False,
     "items_needed": ["1x Quartz Energy SMG", "30x MG Scrip", "5x Ace Interceptor Helmet", "35x Tundra Kopion Horn"],
     "reward": ['1x Quartz "Jungle Camo" Energy SMG'],
     "image": "https://media.starcitizen.tools/d/d7/Quartz_Jungle_Camo_Energy_SMG_skin.png"},
    {"id": "make-gun-sandy", "name": "Make gun sandy", "category": "Weapons", "active": False,
     "items_needed": ["1x Quartz Energy SMG", "30x Council Scrip", "5x Ace Interceptor Helmet", "10x Advocacy Badge (Replica)"],
     "reward": ['1x Quartz "Hunter Camo" Energy SMG'],
     "image": "https://media.starcitizen.tools/f/ff/Quartz_Hunter_Camo.png"},
    {"id": "prettify-karna-gun", "name": "Prettify Karna Gun", "category": "Weapons", "active": False,
     "items_needed": ["1x Karna Rifle", "10x Irradiated Valakkar Fang (Adult)", "10x Irradiated Valakkar Fang (Juvenile)", "10x Irradiated Kopion Horn", "1x Irradiated Valakkar Pearl (Grade AAA)"],
     "reward": ['1x Karna "Ascension" Rifle'],
     "image": "https://media.starcitizen.tools/3/38/Prettify_Karna_Gun.png"},
    {"id": "built-on-s71", "name": "Built on S71 rifle", "category": "Weapons", "active": False,
     "items_needed": ["1x S71 Rifle", "10x Carinite", "10x Saldynium (Ore)", "10x Jaclium (Ore)", "1x Carinite (Pure)"],
     "reward": ['1x S71 "Ascension" Rifle'],
     "image": "https://media.starcitizen.tools/6/64/Built_on_S71_rifle.png"},
    {"id": "fix-up-coda-gun", "name": "Fix up Coda gun", "category": "Weapons", "active": False,
     "items_needed": ["1x Coda Pistol", "5x Ace Interceptor Helmet", "1x Tevarin War Service Marker (Pristine)", "30x MG Scrip"],
     "reward": ['1x Coda "Ascension" Pistol'],
     "image": "https://media.starcitizen.tools/7/7b/Fix_up_Coda_gun.png"},
    {"id": "f55-look-better", "name": "F55 Look Better", "category": "Weapons", "active": False,
     "items_needed": ["1x F55 LMG", "4x Yormandi Eye", "2x Yormandi Tongue", "20x Carinite"],
     "reward": ['1x F55 "Mark I" LMG'],
     "image": "https://media.starcitizen.tools/0/06/F55_Look_Better.png"},
    {"id": "hot-shot", "name": "Hot Shot", "category": "Weapons", "active": True,
     "items_needed": ["1x Tripledown Pistol", "20x Bluemoon Fungus", "20x Carinite"],
     "reward": ['1x TripleDown "Heatwave" Pistol'],
     "image": "https://media.starcitizen.tools/0/03/Hot_Shot.jpg"},

    # === UTILITY ITEMS ===
    {"id": "want-better-eyes", "name": "Want Better Eyes", "category": "Utility", "active": False,
     "items_needed": ["1x Wikelo Favor", "2x Yormandi Eye", "1x Yormandi Tongue"],
     "reward": ['1x XDL "Mark I" Monocular Rangefinder'],
     "image": "https://media.starcitizen.tools/3/37/Want_Better_Eyes.png"},

    # === ARMOR ===
    {"id": "xian-xanthule-suit", "name": "Xi'an Xanthule Suit made better", "category": "Armor", "active": False,
     "items_needed": ["1x Xanthule Suit", "1x Xanthule Helmet", "10x Ace Interceptor Helmet", "1x Tevarin War Service Marker (Pristine)", "20x MG Scrip"],
     "reward": ["1x Xanthule Ascension Helmet", "1x Xanthule Ascension Suit"],
     "image": "https://media.starcitizen.tools/9/93/Xi%27an_Xanthule_Suit_made_better.png"},
    {"id": "walk-in-danger", "name": "Walk in danger. Look good.", "category": "Armor", "active": False,
     "items_needed": ["1x Novikov Exploration Suit", "1x Novikov Helmet", "30x MG Scrip", "10x Irradiated Valakkar Fang (Adult)", "20x Irradiated Valakkar Fang (Juvenile)", "1x Irradiated Valakkar Pearl (Grade AAA)"],
     "reward": ['1x Novikov "Ascension" Helmet', '1x Novikov "Ascension" Exploration Suit'],
     "image": "https://media.starcitizen.tools/e/e2/Walk_in_danger.png"},
    {"id": "adventure-a-venture", "name": "Adventure a A-Venture", "category": "Armor", "active": False,
     "items_needed": ["1x Venture Arms", "1x Venture Core", "1x Venture Helmet White", "1x Venture Legs", "30x MG Scrip", "10x Saldynium (Ore)", "10x Jaclium (Ore)", "1x Carinite (Pure)"],
     "reward": ["1x Venture Helmet Ascension", "1x Venture Arms Ascension", "1x Venture Core Ascension", "1x Venture Legs Ascension"],
     "image": "https://media.starcitizen.tools/2/27/Adventure_a_a-venture.png"},
    {"id": "test-armor", "name": "Test Armor", "category": "Armor", "active": True,
     "items_needed": ["1x Palatino Helmet", "1x Palatino Arms", "1x Palatino Legs", "1x Palatino Core", "1x Palatino Backpack", "14x Yormandi Eye", "7x Yormandi Tongue"],
     "reward": ["1x Palatino Helmet Mark 1", "1x Palatino Arms Mark 1", "1x Palatino Legs Mark 1", "1x Palatino Core Mark 1", "1x Palatino Backpack Mark 1"],
     "image": "https://media.starcitizen.tools/e/ee/Test_Armor.png"},
    {"id": "hide-snow-suit", "name": "Hide Snow Suit", "category": "Armor", "active": True,
     "items_needed": ["4x ASD Secure Drive", "1x Geist Armor Arms ASD Edition", "1x Geist Armor Core ASD Edition", "1x Geist Armor Helmet ASD Edition", "1x Geist Armor Legs ASD Edition", "1x Geist Backpack ASD Edition"],
     "reward": ["1x Geist Armor Helmet Snow Camo", "1x Geist Backpack Snow Camo", "1x Geist Armor Arms Snow Camo", "1x Geist Armor Core Snow Camo", "1x Geist Armor Legs Snow Camo"],
     "image": "https://media.starcitizen.tools/3/3c/Hide_Snow_Suit.png"},
    {"id": "shiny-builder-suit", "name": "Shiny Builder Suit", "category": "Armor", "active": True,
     "items_needed": ["1x Corbel Helmet Mire", "1x Corbel Core Mire", "1x Corbel Arms Mire", "1x Corbel Legs Mire", "1x Novikov Backpack Mire", "10x ASD Secure Drive", "5x RCMBNT-RGL-1", "5x RCMBNT-RGL-2", "5x RCMBNT-RGL-3"],
     "reward": ["1x Corbel Helmet Crush", "1x Corbel Core Crush", "1x Corbel Arms Crush", "1x Corbel Legs Crush", "1x Novikov Backpack Crush"],
     "image": "https://media.starcitizen.tools/5/54/Shiny_Builder_Suit.png"},
    {"id": "armor-with-vanduul", "name": "Armor with Vanduul", "category": "Armor", "active": True,
     "items_needed": ["1x Testudo Helmet Turfwar", "1x Testudo Core Turfwar", "1x Testudo Arms Turfwar", "1x Testudo Legs Turfwar", "1x Testudo Backpack Turfwar", "15x Vanduul Plating", "15x Vanduul Metal"],
     "reward": ["1x Testudo Helmet Clanguard", "1x Testudo Core Clanguard", "1x Testudo Arms Clanguard", "1x Testudo Legs Clanguard", "1x Testudo Backpack Clanguard"],
     "image": "https://media.starcitizen.tools/c/c5/Armor_with_Vanduul.png"},
    {"id": "want-armor-tree", "name": "Want armor look like tree?", "category": "Armor", "active": False,
     "items_needed": ["3x Wikelo Favor", "5x Ace Interceptor Helmet", "50x Valakkar Fang (Juvenile)", "1x ADP-mk4 Core Woodland", "1x ADP-mk4 Arms Woodland", "1x ADP-mk4 Legs Woodland", "1x ADP-mk4 Helmet Woodland"],
     "reward": ["1x DCP Armor Helmet Jungle Camo", "1x DCP Armor Arms Jungle Camo", "1x DCP Armor Core Jungle Camo", "1x DCP Armor Legs Jungle Camo"],
     "image": "https://media.starcitizen.tools/6/63/%22Want_armor_look_like_tree%3F%22.png"},
    {"id": "look-at-desert", "name": "Look at desert but don't see you", "category": "Armor", "active": False,
     "items_needed": ["3x Wikelo Favor", "5x Ace Interceptor Helmet", "20x Advocacy Badge (Replica)", "1x ADP-mk4 Core Woodland", "1x ADP-mk4 Arms Woodland", "1x ADP-mk4 Legs Woodland", "1x ADP-mk4 Helmet Woodland"],
     "reward": ["1x DCP Armor Helmet Hunter Camo", "1x DCP Armor Arms Hunter Camo", "1x DCP Armor Core Hunter Camo", "1x DCP Armor Legs Hunter Camo"],
     "image": "https://media.starcitizen.tools/c/c7/%22Look_at_desert_but_don%27t_see_you%22.png"},
    {"id": "make-space-navy-armor", "name": "Make space navy armor", "category": "Armor", "active": False,
     "items_needed": ["3x Wikelo Favor", "5x Ace Interceptor Helmet", "50x Grassland Quasi Grazer Egg", "1x ADP-mk4 Core Woodland", "1x ADP-mk4 Arms Woodland", "1x ADP-mk4 Legs Woodland", "1x ADP-mk4 Helmet Woodland"],
     "reward": ["1x DCP Armor Helmet Cobalt Camo", "1x DCP Armor Arms Cobalt Camo", "1x DCP Armor Core Cobalt Camo", "1x DCP Armor Legs Cobalt Camo"],
     "image": "https://media.starcitizen.tools/d/d0/%22Make_space_navy_armor%22.png"},
    {"id": "armor-horn-string", "name": "Armor with Horn and String", "category": "Armor", "active": True,
     "items_needed": ["1x Carinite (Pure)", "1x Antium Armor Core", "1x Antium Armor Helmet", "1x Antium Armor Legs", "1x Antium Armor Arms"],
     "reward": ["1x Ana Armor Helmet Endro", "1x Ana Armor Core Endro", "1x Ana Armor Arms Endro", "1x Ana Armor Legs Endro"],
     "image": "https://media.starcitizen.tools/b/b0/%22Armor_with_Horn_and_String.png"},
    {"id": "make-glowy-armor", "name": "Make glowy armor", "category": "Armor", "active": True,
     "items_needed": ["1x Irradiated Valakkar Pearl (Grade AAA)", "1x Antium Armor Core", "1x Antium Armor Helmet", "1x Antium Armor Legs", "1x Antium Armor Arms"],
     "reward": ["1x Bokto Helmet", "1x Bokto Arms", "1x Bokto Core", "1x Bokto Legs"],
     "image": "https://media.starcitizen.tools/8/83/Make_glowy_armor.png"},
    {"id": "do-lava-suit", "name": "Do Lava Suit", "category": "Armor", "active": True,
     "items_needed": ["1x Strata Core", "1x Strata Helmet", "1x Strata Legs", "1x Strata Arms", "1x Strata Backpack", "20x Bluemoon Fungus"],
     "reward": ["1x Strata Core Caldera", "1x Strata Helmet Caldera", "1x Strata Legs Caldera", "1x Strata Arms Caldera", "1x Strata Backpack Caldera"],
     "image": None},

    # === VEHICLES ===
    {"id": "noxy-mod", "name": "Noxy Mod", "category": "Vehicles", "active": True,
     "items_needed": ["4x Wikelo Favor"], "reward": ["Nox"], "image": None},
    {"id": "pulse-plus", "name": "Pulse Plus", "category": "Vehicles", "active": True,
     "items_needed": ["4x Wikelo Favor"], "reward": ["Pulse"], "image": None},
    {"id": "make-ursa-mod", "name": "Make a Ursa Mod", "category": "Vehicles", "active": True,
     "items_needed": ["4x Wikelo Favor", "20x Saldynium (Ore)", "20x Jaclium (Ore)"], "reward": ["Ursa Medivac"], "image": None},
    {"id": "where-wolf-here-wolf", "name": "Where Wolf? Here Wolf", "category": "Vehicles", "active": True,
     "items_needed": ["10x Wikelo Favor", "10x Vanduul Plating", "10x Vanduul Metal", "1x Large Artifact Fragment (Pristine)"],
     "reward": ["L-21 Wolf (Stealth Spec)"], "image": None},
    {"id": "most-special-wolf", "name": "Most Special Wolf", "category": "Vehicles", "active": True,
     "req_rank": "Very Good Customer",
     "items_needed": ["5x Wikelo Favor"], "reward": ["L-21 Wolf (Military Spec)", "Antium Helmet Midnight Sun", "Antium Arms Midnight Sun", "Antium Core Midnight Sun", "Antium Legs Midnight Sun", 'Fresnel "Deepwater" Energy LMG'], "image": None},
    {"id": "golem-rocks", "name": "Golem Rocks", "category": "Vehicles", "active": True,
     "items_needed": ["2x Wikelo Favor", "15x ASD Secure Drive"], "reward": ["Golem"], "image": None},
    {"id": "upgrade-intrepid", "name": "Upgrade Intrepid", "category": "Vehicles", "active": True,
     "items_needed": ["3x Wikelo Favor", "1x Government Cartography Agency Medal (Pristine)"], "reward": ["Intrepid"], "image": None},
    {"id": "fortune-ship", "name": "Fortune ship for you", "category": "Vehicles", "active": True,
     "items_needed": ["3x Wikelo Favor", "1x Carinite (Pure)"], "reward": ["Fortune"], "image": None},
    {"id": "spirit-cargo-mod", "name": "Spirit Cargo mod", "category": "Vehicles", "active": True,
     "items_needed": ["8x Wikelo Favor", "1x Tevarin War Service Marker (Pristine)"], "reward": ["C1 Spirit"], "image": None},
    {"id": "zeus-special", "name": "Zeus Special", "category": "Vehicles", "active": True,
     "items_needed": ["10x Wikelo Favor", "1x UEE 6th Platoon Medal (Pristine)"], "reward": ["Zeus Mk II ES"], "image": None},
    {"id": "zeus-cargo-special", "name": "Zeus Cargo Special", "category": "Vehicles", "active": True,
     "items_needed": ["20x Wikelo Favor", "15x Carinite", "10x Ace Interceptor Helmet", "2x Carinite (Pure)"], "reward": ["Zeus Mk II CL"], "image": None},
    {"id": "more-than-max", "name": "More than a Max", "category": "Vehicles", "active": True,
     "items_needed": ["30x Wikelo Favor", "10x Ace Interceptor Helmet", "3x Carinite (Pure)", "3x Irradiated Valakkar Pearl (Grade AAA)"], "reward": ["Starlancer MAX"], "image": None},
    {"id": "want-taurus", "name": "Want Taurus ship", "category": "Vehicles", "active": True,
     "items_needed": ["30x Wikelo Favor", "3x Carinite (Pure)", "3x Irradiated Valakkar Pearl (Grade AAA)", "3x Government Cartography Agency Medal (Pristine)"], "reward": ["Constellation Taurus"], "image": None},
    {"id": "ready-for-raft", "name": "Ready for Raft?", "category": "Vehicles", "active": True,
     "items_needed": ["8x Wikelo Favor", "10x Irradiated Valakkar Fang (Adult)", "20x Irradiated Valakkar Fang (Juvenile)", "5x Irradiated Kopion Horn", "1x Irradiated Valakkar Pearl (Grade AAA)"], "reward": ["Argo Raft"], "image": None},
    {"id": "prospects-look-good", "name": "Prospects Look Good", "category": "Vehicles", "active": True,
     "items_needed": ["6x Wikelo Favor", "20x Carinite", "30x Saldynium (Ore)", "40x Jaclium (Ore)", "1x Carinite (Pure)"], "reward": ["MISC Prospector"], "image": None},
    {"id": "peregrine-mod", "name": "Peregrine Wikelo Mod", "category": "Vehicles", "active": True,
     "items_needed": ["4x Wikelo Favor", "1x DCHS-05 Orbital Positioning Comp-Board"], "reward": ["Sabre Peregrine"], "image": None},
    {"id": "firebird-mod", "name": "Firebird Mod", "category": "Vehicles", "active": True,
     "items_needed": ["15x Wikelo Favor", "4x DCHS-05 Orbital Positioning Comp-Board", "3x Ace Interceptor Helmet", "1x Government Cartography Agency Medal (Pristine)"], "reward": ["Sabre Firebird"], "image": None},
    {"id": "build-mod-scorpius", "name": "Build a Mod Scorpius", "category": "Vehicles", "active": True,
     "items_needed": ["15x Wikelo Favor", "4x DCHS-05 Orbital Positioning Comp-Board", "1x Tevarin War Service Marker (Pristine)"], "reward": ["Scorpius"], "image": None},
    {"id": "wikelo-navy-f7", "name": "Wikelo Navy F7", "category": "Vehicles", "active": True,
     "items_needed": ["16x Wikelo Favor", "3x DCHS-05 Orbital Positioning Comp-Board", "5x Ace Interceptor Helmet", "1x Government Cartography Agency Medal (Pristine)"], "reward": ["F7C-M Super Hornet Mk II"], "image": None},
    {"id": "guardian-fight-mod", "name": "Guardian Fight Mod", "category": "Vehicles", "active": True,
     "items_needed": ["20x Wikelo Favor", "15x Irradiated Valakkar Pearl (Grade AA)", "10x Ace Interceptor Helmet", "1x Tevarin War Service Marker (Pristine)"], "reward": ["Guardian"], "image": None},
    {"id": "guardian-take-down", "name": "Guardian take down ship", "category": "Vehicles", "active": True,
     "items_needed": ["25x Wikelo Favor", "15x Irradiated Valakkar Pearl (Grade AA)", "15x DCHS-05 Orbital Positioning Comp-Board", "2x UEE 6th Platoon Medal (Pristine)"], "reward": ["Guardian QI"], "image": None},
    {"id": "guardian-wik-x", "name": "Guardian Wik-X", "category": "Vehicles", "active": True,
     "items_needed": ["25x Wikelo Favor", "15x Ace Interceptor Helmet", "2x Large Artifact Fragment (Pristine)", "30x Vanduul Plating", "30x Vanduul Metal"], "reward": ["Guardian MX"], "image": None},
    {"id": "f8-war-mod", "name": "F8 War Mod", "category": "Vehicles", "active": True,
     "items_needed": ["40x Wikelo Favor", "4x Carinite (Pure)", "4x Irradiated Valakkar Pearl (Grade AAA)", "4x Tevarin War Service Marker (Pristine)"], "reward": ["F8C Lightning (Military Spec)"], "image": None},
    {"id": "sneaky-stabber", "name": "Sneaky Stabber", "category": "Vehicles", "active": True,
     "items_needed": ["40x Wikelo Favor", "15x DCHS-05 Orbital Positioning Comp-Board", "3x Carinite (Pure)", "3x Irradiated Valakkar Pearl (Grade AAA)"], "reward": ["F8C Lightning (Stealth Spec)"], "image": None},
    {"id": "what-is-terrapin", "name": "What is Terrapin?", "category": "Vehicles", "active": True,
     "items_needed": ["15x Wikelo Favor", "10x ASD Secure Drive", "1x Tevarin War Service Marker (Pristine)"], "reward": ["Terrapin Medic"], "image": None},
    {"id": "new-move-big-starlancer", "name": "New Move Big Starlancer Ship", "category": "Vehicles", "active": True,
     "items_needed": ["50x Wikelo Favor", "15x Ace Interceptor Helmet", "30x ASD Secure Drive", "3x Irradiated Valakkar Pearl (Grade AAA)", "3x Tevarin War Service Marker (Pristine)", "3x Carinite (Pure)", "3x DCHS-05 Orbital Positioning Comp-Board"],
     "reward": ["Starlancer TAC"], "image": None},
    {"id": "starfighter-inferno", "name": "Starfighter Inferno Special", "category": "Vehicles", "active": True,
     "items_needed": ["10x Wikelo Favor", "5x Yormandi Tongue", "5x Ace Interceptor Helmet", "1x UEE 6th Platoon Medal (Pristine)"], "reward": ["Ares Star Fighter Inferno"], "image": None},
    {"id": "sneaky-starfighter-ion", "name": "Sneaky Starfighter Ion", "category": "Vehicles", "active": True,
     "items_needed": ["10x Wikelo Favor", "10x Yormandi Eye", "5x Ace Interceptor Helmet", "1x Tevarin War Service Marker (Pristine)"], "reward": ["Ares Star Fighter Ion"], "image": None},
    {"id": "prowler-more-utility", "name": "Prowler More Utility", "category": "Vehicles", "active": True,
     "items_needed": ["40x Wikelo Favor", "20x Yormandi Eye", "10x Yormandi Tongue", "3x Irradiated Valakkar Pearl (Grade AAA)", "3x Carinite (Pure)"], "reward": ["Prowler Utility"], "image": None},
    {"id": "starlifter-a2-war-mod", "name": "Starlifter A2 War Mod", "category": "Vehicles", "active": True,
     "items_needed": ["50x Wikelo Favor", "20x Polaris Bit", "20x MG Scrip", "6x ASD Secure Drive", "6x Irradiated Valakkar Pearl (Grade AAA)", "6x Tevarin War Service Marker (Pristine)", "6x DCHS-05 Orbital Positioning Comp-Board", "6x Carinite (Pure)"],
     "reward": ["A2 Hercules Starlifter"], "image": None},
    {"id": "asgard-fight-mod", "name": "Asgard Fight Mod", "category": "Vehicles", "active": True,
     "items_needed": ["50x Wikelo Favor", "3x ASD Secure Drive", "5x RCMBNT-PWL-1", "5x RCMBNT-PWL-2", "5x RCMBNT-PWL-3", "5x RCMBNT-RGL-1", "5x RCMBNT-RGL-2", "5x RCMBNT-RGL-3", "5x RCMBNT-XTL-1", "5x RCMBNT-XTL-2", "5x RCMBNT-XTL-3"],
     "reward": ["Asgard"], "image": None},
    {"id": "rsi-meteor-mod", "name": "RSI Meteor Mod", "category": "Vehicles", "active": True,
     "items_needed": ["10x Wikelo Favor", "5x Ace Interceptor Helmet", "1x Large Artifact Fragment (Pristine)", "10x Vanduul Plating", "10x Vanduul Metal"], "reward": ["Meteor"], "image": None},
    {"id": "now-make-polaris", "name": "Now make Polaris. Short Time Deal.", "category": "Vehicles", "active": True,
     "items_needed": ["50x Wikelo Favor", "20x Carinite", "20x Irradiated Valakkar Fang (Apex)", "20x MG Scrip", "15x Polaris Bit", "15x ASD Secure Drive", "15x Ace Interceptor Helmet", "15x Irradiated Valakkar Pearl (Grade AAA)", "15x UEE 6th Platoon Medal (Pristine)", "15x Carinite (Pure)", "10x DCHS-05 Orbital Positioning Comp-Board", "1x RCMBNT-PWL-1", "1x RCMBNT-PWL-2", "1x RCMBNT-PWL-3", "1x RCMBNT-RGL-1", "1x RCMBNT-RGL-2", "1x RCMBNT-RGL-3", "1x RCMBNT-XTL-1", "1x RCMBNT-XTL-2", "1x RCMBNT-XTL-3"],
     "reward": ["Polaris Wikelo Special"], "image": None},
    {"id": "aegis-idris-p", "name": "AEGIS Idris P", "category": "Vehicles", "active": True,
     "req_rank": "Very Best Customer",
     "items_needed": ["50x Wikelo Favor", "50x Polaris Bit", "50x DCHS-05 Orbital Positioning Comp-Board", "50x Carinite", "50x Irradiated Valakkar Fang (Apex)", "50x MG Scrip", "50x Ace Interceptor Helmet", "30x ASD Secure Drive", "30x Irradiated Valakkar Pearl (Grade AAA)", "30x UEE 6th Platoon Medal (Pristine)", "30x Carinite (Pure)", "5x RCMBNT-PWL-1", "5x RCMBNT-PWL-2", "5x RCMBNT-PWL-3", "5x RCMBNT-RGL-1", "5x RCMBNT-RGL-2", "5x RCMBNT-RGL-3", "5x RCMBNT-XTL-1", "5x RCMBNT-XTL-2", "5x RCMBNT-XTL-3"],
     "reward": ["Idris-P"], "image": None},
]
